In [1]:
import pandas as pd
import numpy as np

from nba_api.stats.static import players
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playercareerstats
from nba_api.stats.endpoints import playergamelogs
from nba_api.stats.endpoints import teamgamelogs

In [5]:
# https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/static/players.md
players.find_players_by_first_name('LeBron')

[{'id': 2544,
  'full_name': 'LeBron James',
  'first_name': 'LeBron',
  'last_name': 'James',
  'is_active': True}]

In [6]:
# Career stats
# https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/playercareerstats.md

lebron_stats = playercareerstats.PlayerCareerStats(player_id = '2544')
lebron_df = lebron_stats.get_data_frames()[0]
lebron_df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,...,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,...,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,...,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,...,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,...,0.712,133,459,592,539,138,81,255,165,2250
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,3054.0,789,...,0.780,106,507,613,587,137,93,241,139,2304
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,2966.0,768,...,0.767,71,483,554,651,125,77,261,119,2258
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,3063.0,758,...,0.759,80,510,590,554,124,50,284,163,2111
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,2326.0,621,...,0.771,94,398,492,387,115,50,213,96,1683
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,2877.0,765,...,0.753,97,513,610,551,129,67,226,110,2036
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,2902.0,767,...,0.750,81,452,533,488,121,26,270,126,2089
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,2493.0,624,...,0.710,51,365,416,511,109,49,272,135,1743
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,2709.0,737,...,0.731,111,454,565,514,104,49,249,143,1920
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,2795.0,736,...,0.674,97,542,639,646,92,44,303,134,1954
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,3026.0,857,...,0.731,97,612,709,747,116,71,347,136,2251
15,2544,2018-19,00,1610612747,LAL,34.0,55,55,1937.0,558,...,0.665,57,408,465,454,72,33,197,94,1505
16,2544,2019-20,00,1610612747,LAL,35.0,67,67,2316.0,643,...,0.693,66,459,525,684,78,36,261,118,1698
17,2544,2020-21,00,1610612747,LAL,36.0,45,45,1504.0,422,...,0.698,29,317,346,350,48,25,168,70,1126
18,2544,2021-22,00,1610612747,LAL,37.0,56,56,2084.0,640,...,0.756,63,396,459,349,73,59,196,121,1695
19,2544,2022-23,00,1610612747,LAL,37.0,23,23,832.0,245,...,0.726,31,163,194,153,27,15,70,42,624

In [17]:
# Player Game Log
# https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/playergamelogs.md

lebron_games = playergamelogs.PlayerGameLogs(
    player_id_nullable = '2544',
    season_nullable = '2017-18'
)
lebron_games_df = lebron_games.get_data_frames()[0]
lebron_games_df

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,VIDEO_AVAILABLE_FLAG
0,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021701220,2018-04-11T00:00:00,CLE vs. NYK,...,33,1,69,81,31,82,53,19,82,1
1,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021701207,2018-04-09T00:00:00,CLE @ NYK,...,33,39,37,45,13,59,1,19,55,1
2,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021701183,2018-04-06T00:00:00,CLE @ PHI,...,79,1,11,2,26,3,1,1,2,1
3,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021701176,2018-04-05T00:00:00,CLE vs. WAS,...,33,39,25,16,16,32,1,19,22,1
4,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021701156,2018-04-03T00:00:00,CLE vs. TOR,...,1,39,4,40,18,64,1,19,61,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021700058,2017-10-25T00:00:00,CLE @ BKN,...,69,15,25,33,51,13,1,1,17,1
78,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021700049,2017-10-24T00:00:00,CLE vs. CHI,...,33,15,25,13,26,20,1,19,19,2
79,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021700028,2017-10-21T00:00:00,CLE vs. ORL,...,1,1,50,63,80,75,53,19,76,1
80,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021700021,2017-10-20T00:00:00,CLE @ MIL,...,1,39,78,55,16,64,53,19,64,1
81,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021700001,2017-10-17T00:00:00,CLE vs. BOS,...,33,66,37,33,37,17,1,19,19,1

In [18]:
# Team Game Log
# https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/teamgamelogs.md

cavs_games = teamgamelogs.TeamGameLogs(
    team_id_nullable = '1610612739',
    season_nullable = '2017-18'
)
cavs_games_df = cavs_games.get_data_frames()[0]
cavs_games_df

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,2017-18,1610612739,CLE,Cleveland Cavaliers,0021701220,2018-04-11T00:00:00,CLE vs. NYK,L,48.0,37,...,11,79,60,15,45,20,17,28,69,66
1,2017-18,1610612739,CLE,Cleveland Cavaliers,0021701207,2018-04-09T00:00:00,CLE @ NYK,W,48.0,40,...,40,8,16,15,60,71,17,38,12,13
2,2017-18,1610612739,CLE,Cleveland Cavaliers,0021701183,2018-04-06T00:00:00,CLE @ PHI,L,48.0,45,...,46,36,48,47,60,71,52,16,4,51
3,2017-18,1610612739,CLE,Cleveland Cavaliers,0021701176,2018-04-05T00:00:00,CLE vs. WAS,W,48.0,42,...,71,18,60,10,45,71,6,16,22,41
4,2017-18,1610612739,CLE,Cleveland Cavaliers,0021701156,2018-04-03T00:00:00,CLE vs. TOR,W,48.0,38,...,40,71,25,28,11,2,31,16,43,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2017-18,1610612739,CLE,Cleveland Cavaliers,0021700058,2017-10-25T00:00:00,CLE @ BKN,L,48.0,39,...,14,56,81,57,3,20,31,28,50,58
78,2017-18,1610612739,CLE,Cleveland Cavaliers,0021700049,2017-10-24T00:00:00,CLE vs. CHI,W,48.0,43,...,59,10,4,57,45,20,6,38,22,24
79,2017-18,1610612739,CLE,Cleveland Cavaliers,0021700028,2017-10-21T00:00:00,CLE vs. ORL,L,48.0,33,...,31,79,60,67,3,63,6,3,77,77
80,2017-18,1610612739,CLE,Cleveland Cavaliers,0021700021,2017-10-20T00:00:00,CLE @ MIL,W,48.0,44,...,31,24,70,28,45,6,2,69,28,9
81,2017-18,1610612739,CLE,Cleveland Cavaliers,0021700001,2017-10-17T00:00:00,CLE vs. BOS,W,48.0,38,...,7,65,67,77,26,37,75,13,59,43

In [15]:
la_games_df.columns

Index(['SEASON_YEAR', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK',
       'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK',
       'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK',
       'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK',
       'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK'],
      dtype='object')

1. Get teams list and players list (active)
2. Get player career stats
3. Get all team games for specific season
4. Get player stats per game

In [2]:
players_list = players.get_active_players()
players_df = pd.DataFrame(players_list)
players_df.to_csv('players.csv')

In [6]:
players_df

          id         full_name first_name  last_name  is_active
0    1630173  Precious Achiuwa   Precious    Achiuwa       True
1     203500      Steven Adams     Steven      Adams       True
2    1628389       Bam Adebayo        Bam    Adebayo       True
3    1630534      Ochai Agbaji      Ochai     Agbaji       True
4    1630583      Santi Aldama      Santi     Aldama       True
..       ...               ...        ...        ...        ...
577   201152    Thaddeus Young   Thaddeus      Young       True
578  1629027        Trae Young       Trae      Young       True
579  1630209    Omer Yurtseven       Omer  Yurtseven       True
580   203469       Cody Zeller       Cody     Zeller       True
581  1627826       Ivica Zubac      Ivica      Zubac       True

[582 rows x 5 columns]

In [3]:
teams_list = teams.get_teams()
teams_df = pd.DataFrame(teams_list)
teams_df.to_csv('teams.csv')

In [4]:
#players_list[0]
player_dfs = []
for player in players_list[:10]:
    player_id = player['id']
    player_season_stats_df = playercareerstats.PlayerCareerStats(
        player_id = player_id,
        per_mode36 = 'PerGame'
    ).get_data_frames()[0]
    player_season_stats_df['PLAYER_NAME'] = player['full_name']
    player_dfs.append(player_season_stats_df)

all_player_dfs = pd.concat(player_dfs)
all_player_dfs

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLAYER_NAME
0,1630173,2020-21,00,1610612748,MIA,21.0,61,4,12.1,2.0,...,1.2,2.2,3.4,0.5,0.3,0.5,0.7,1.5,5.0,Precious Achiuwa
1,1630173,2021-22,00,1610612761,TOR,22.0,73,28,23.6,3.6,...,2.0,4.5,6.5,1.1,0.5,0.6,1.2,2.1,9.1,Precious Achiuwa
2,1630173,2022-23,00,1610612761,TOR,23.0,12,0,20.4,3.0,...,2.0,5.0,7.0,1.3,0.2,0.6,1.3,1.6,8.8,Precious Achiuwa
0,203500,2013-14,00,1610612760,OKC,20.0,81,20,14.8,1.1,...,1.8,2.3,4.1,0.5,0.5,0.7,0.9,2.5,3.3,Steven Adams
1,203500,2014-15,00,1610612760,OKC,21.0,70,67,25.3,3.1,...,2.8,4.6,7.5,0.9,0.5,1.2,1.4,3.2,7.7,Steven Adams
2,203500,2015-16,00,1610612760,OKC,22.0,80,80,25.2,3.3,...,2.7,3.9,6.7,0.8,0.5,1.1,1.1,2.8,8.0,Steven Adams
3,203500,2016-17,00,1610612760,OKC,23.0,80,80,29.9,4.7,...,3.5,4.2,7.7,1.1,1.1,1.0,1.8,2.4,11.3,Steven Adams
4,203500,2017-18,00,1610612760,OKC,24.0,76,76,32.7,5.9,...,5.1,4.0,9.0,1.2,1.2,1.0,1.7,2.8,13.9,Steven Adams
5,203500,2018-19,00,1610612760,OKC,25.0,80,80,33.4,6.0,...,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9,Steven Adams
6,203500,2019-20,00,1610612760,OKC,26.0,63,63,26.7,4.5,...,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9,Steven Adams
7,203500,2020-21,00,1610612740,NOP,27.0,58,58,27.7,3.3,...,3.7,5.2,8.9,1.9,0.9,0.7,1.3,1.9,7.6,Steven Adams
8,203500,2021-22,00,1610612763,MEM,28.0,76,75,26.3,2.8,...,4.6,5.4,10.0,3.4,0.9,0.8,1.5,2.0,6.9,Steven Adams
9,203500,2022-23,00,1610612763,MEM,29.0,31,31,26.5,3.5,...,4.9,5.6,10.5,2.2,0.8,1.1,1.9,2.3,7.9,Steven Adams
0,1628389,2017-18,00,1610612748,MIA,20.0,69,19,19.8,2.5,...,1.7,3.8,5.5,1.5,0.5,0.6,1.0,2.0,6.9,Bam Adebayo
1,1628389,2018-19,00,1610612748,MIA,21.0,82,28,23.3,3.4,...,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9,Bam Adebayo
2,1628389,2019-20,00,1610612748,MIA,22.0,72,72,33.6,6.1,...,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9,Bam Adebayo
3,1628389,2020-21,00,1610612748,MIA,23.0,64,64,33.5,7.1,...,2.2,6.7,9.0,5.4,1.2,1.0,2.6,2.3,18.7,Bam Adebayo
4,1628389,2021-22,00,1610612748,MIA,24.0,56,56,32.6,7.3,...,2.4,7.6,10.1,3.4,1.4,0.8,2.6,3.1,19.1,Bam Adebayo
5,1628389,2022-23,00,1610612748,MIA,25.0,32,32,35.1,8.3,...,2.6,7.2,9.8,3.2,1.0,0.7,3.1,3.2,20.9,Bam Adebayo
0,1630534,2022-23,00,1610612762,UTA,22.0,16,0,7.9,1.1,...,0.4,0.7,1.1,0.2,0.1,0.0,0.0,0.8,2.7,Ochai Agbaji
0,1630583,2021-22,00,1610612763,MEM,21.0,32,0,11.2,1.7,...,1.0,1.7,2.7,0.7,0.2,0.3,0.5,1.1,4.1,Santi Aldama
1,1630583,2022-23,00,1610612763,MEM,21.0,33,16,23.3,3.4,...,1.2,4.0,5.2,1.3,0.7,0.9,0.6,2.3,9.6,Santi Aldama
0,1629638,2019-20,00,1610612740,NOP,21.0,47,1,12.6,2.1,...,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7,Nickeil Alexander-Walker
1,1629638,2020-21,00,1610612740,NOP,22.0,46,13,21.9,4.2,...,0.3,2.8,3.1,2.2,1.0,0.5,1.5,1.9,11.0,Nickeil Alexander-Walker
2,1629638,2021-22,00,1610612740,NOP,23.0,50,19,26.3,4.7,...,0.7,2.6,3.3,2.8,0.8,0.4,1.7,1.8,12.8,Nickeil Alexander-Walker
3,1629638,2021-22,00,1610612762,UTA,23.0,15,2,9.9,1.1,...,0.1,1.5,1.5,1.1,0.3,0.3,0.5,1.0,3.5,Nickeil Alexander-Walker
4,1629638,2021-22,00,0,TOT,23.0,65,21,22.6,3.9,...,0.6,2.3,2.9,2.4,0.7,0.4,1.4,1.6,10.6,Nickeil Alexander-Walker
5,1629638,2022-23,00,1610612762,UTA,24.0,26,2,15.5,2.5,...,0.3,1.3,1.6,2.3,0.7,0.4,1.3,1.7,6.8,Nickeil Alexander-Walker
0,1628960,2018-19,00,1610612762,UTA,23.0,38,2,11.0,1.8,...,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6,Grayson Allen
1,1628960,2019-20,00,1610612763,MEM,24.0,38,0,18.9,3.1,...,0.2,2.0,2.2,1.4,0.3,0.1,0.9,1.4,8.7,Grayson Allen
2,1628960,2020-21,00,1610612763,MEM,25.0,50,38,25.2,3.5,...,0.4,2.8,3.2,2.2,0.9,0.2,1.0,1.4,10.6,Grayson Allen
3,1628960,2021-22,00,1610612749,MIL,26.0,66,61,27.3,3.9,...,0.5,2.9,3.4,1.5,0.7,0.3,0.7,1.5,11.1,Grayson Allen
4,1628960,2022-23,00,1610612749,MIL,27.0,32,30,27.4,3.3,...,1.0,2.6,3.6,2.4,0.7,0.2,1.1,1.4,10.2,Grayson Allen
0,1628386,2017-18,00,1610612751,BKN,20.0,72,31,20.0,3.3,...,2.0,3.4,5.4,0.7,0.4,1.2,1.1,2.0,8.2,Jarrett Allen
1,1628386,2018-19,00,1610612751,BKN,21.0,80,80,26.2,4.2,...,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9,Jarrett Allen
2,1628386,2019-20,00,1610612751,BKN,22.0,70,64,26.5,4.3,...,3.1,6.5,9.6,1.6,0.6,1.3,1.1,2.3,11.1,Jarrett Allen
3,1628386,2020-21,00,1610612751,BKN,23.0,12,5,26.6,3.7,...,3.2,7.3,10.4,1.7,0.6,1.6,1.8,1.8,11.2,Jarrett Allen
4,1628386,2020-21,00,1610612739,CLE,23.0,51,40,30.3,5.0,...,3.1,6.8,9.9,1.7,0.5,1.4,1.5,1.5,13.2,Jarrett Allen
5,1628386,2020-21,00,0,TOT,23.0,63,45,29.6,4.7,...,3.1,6.9,10.0,1.7,0.5,1.4,1.6,1.5,12.8,Jarrett Allen
6,1628386,2021-22,00,1610612739,CLE,24.0,56,56,32.3,6.6,...,3.4,7.3,10.8,1.6,0.8,1.3,1.7,1.7,16.1,Jarrett Allen
7,1628386,2022-23,00,1610612739,CLE,24.0,29,29,33.5,5.6,...,3.0,7.2,10.2,1.4,0.8,1.2,1.5,2.2,14.0,Jarrett Allen
0,1630631,2021-22,00,1610612740,NOP,24.0,54,1,15.4,2.4,...,0.5,1.4,1.9,2.8,1.3,0.1,0.7,1.4,6.1,Jose Alvarado
1,1630631,2022-23,00,1610612740,NOP,24.0,34,7,20.7,3.3,...,0.5,1.8,2.3,3.0,1.4,0.1,1.4,2.1,9.0,Jose Alvarado
0,203937,2014-15,00,1610612759,SAS,21.0,33,8,10.9,0.9,...,0.2,2.0,2.2,0.8,0.5,0.2,0.3,0.8,2.2,Kyle Anderson
1,203937,2015-16,00,1610612759,SAS,22.0,78,11,16.0,1.8,...,0.3,2.8,3.1,1.6,0.8,0.4,0.8,1.2,4.5,Kyle Anderson
2,203937,2016-17,00,1610612759,SAS,23.0,72,14,14.2,1.3,...,0.5,2.4,2.9,1.3,0.7,0.4,0.5,0.9,3.4,Kyle Anderson
3,203937,2017-18,00,1610612759,SAS,24.0,74,67,26.7,3.1,...,1.1,4.2,5.4,2.7,1.6,0.8,1.3,1.5,7.9,Kyle Anderson
4,203937,2018-19,00,1610612763,MEM,25.0,43,40,29.8,3.5,...,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0,Kyle Anderson
5,203937,2019-20,00,1610612763,MEM,26.0,67,28,19.8,2.3,...,0.9,3.4,4.3,2.4,0.8,0.6,1.0,1.7,5.8,Kyle Anderson
6,203937,2020-21,00,1610612763,MEM,27.0,69,69,27.4,4.5,...,0.8,5.0,5.7,3.6,1.2,0.8,1.2,1.7,12.4,Kyle Anderson
7,203937,2021-22,00,1610612763,MEM,28.0,69,11,21.5,3.0,...,1.0,4.3,5.3,2.7,1.1,0.7,1.0,1.6,7.6,Kyle Anderson
8,203937,2022-23,00,1610612750,MIN,29.0,26,11,24.3,2.7,...,0.5,3.6,4.1,3.4,1.1,0.8,1.4,2.0,7.3,Kyle Anderson

In [5]:
all_player_dfs.columns

Index(['PLAYER_ID', 'SEASON_ID', 'LEAGUE_ID', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS', 'PLAYER_NAME'],
      dtype='object')

In [8]:
cavs_games = teamgamelogs.TeamGameLogs(
    team_id_nullable = '1610612739',
    season_nullable = '2022-23'
)
cavs_games_df = cavs_games.get_data_frames()[0]
cavs_games_df

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200524,2022-12-29T00:00:00,CLE @ IND,L,48.0,50,...,14,5,9,10,13,34,10,28,4,30
1,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200498,2022-12-26T00:00:00,CLE vs. BKN,L,48.0,39,...,35,27,11,6,21,13,3,9,10,29
2,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200484,2022-12-23T00:00:00,CLE vs. TOR,L,48.0,39,...,32,8,21,4,13,2,10,22,24,31
3,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200466,2022-12-21T00:00:00,CLE vs. MIL,W,48.0,41,...,29,22,5,6,21,22,24,14,14,17
4,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200452,2022-12-19T00:00:00,CLE vs. UTA,W,48.0,43,...,13,16,36,27,13,2,18,16,6,5
5,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200440,2022-12-17T00:00:00,CLE vs. DAL,W,53.0,40,...,1,20,12,19,7,25,34,22,32,21
6,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200431,2022-12-16T00:00:00,CLE vs. IND,W,48.0,38,...,33,20,5,19,29,13,7,16,9,20
7,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200421,2022-12-14T00:00:00,CLE @ DAL,W,48.0,41,...,17,9,3,27,29,8,18,33,26,7
8,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200406,2022-12-12T00:00:00,CLE @ SAS,L,48.0,45,...,14,27,21,10,3,2,1,25,22,23
9,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200390,2022-12-10T00:00:00,CLE vs. OKC,W,48.0,40,...,5,10,12,19,13,25,3,6,23,17
10,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200381,2022-12-09T00:00:00,CLE vs. SAC,L,48.0,34,...,31,30,32,10,13,22,30,16,34,31
11,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200360,2022-12-06T00:00:00,CLE vs. LAL,W,48.0,48,...,14,10,1,1,21,25,18,34,13,8
12,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200348,2022-12-04T00:00:00,CLE @ NYK,L,48.0,29,...,26,34,29,10,5,8,7,30,36,31
13,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200330,2022-12-02T00:00:00,CLE vs. ORL,W,48.0,41,...,35,22,12,10,7,13,3,34,24,12
14,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200312,2022-11-30T00:00:00,CLE vs. PHI,W,48.0,45,...,24,7,29,2,21,1,1,36,19,2
15,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200303,2022-11-28T00:00:00,CLE @ TOR,L,48.0,34,...,10,27,5,10,21,22,16,29,35,34
16,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200295,2022-11-27T00:00:00,CLE @ DET,W,48.0,33,...,22,35,18,35,13,25,18,6,29,17
17,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200280,2022-11-25T00:00:00,CLE @ MIL,L,48.0,34,...,22,36,3,4,29,35,10,16,29,35
18,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200261,2022-11-23T00:00:00,CLE vs. POR,W,48.0,41,...,26,22,24,32,13,13,3,11,14,6
19,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200248,2022-11-21T00:00:00,CLE vs. ATL,W,48.0,42,...,29,16,32,6,21,8,10,21,14,11
20,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200244,2022-11-20T00:00:00,CLE vs. MIA,W,48.0,44,...,4,3,32,10,34,8,30,30,19,3
21,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200225,2022-11-18T00:00:00,CLE vs. CHA,W,58.0,49,...,3,10,32,6,2,25,35,1,1,14
22,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200216,2022-11-16T00:00:00,CLE @ MIL,L,48.0,36,...,33,22,1,10,3,25,16,30,33,35
23,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200193,2022-11-13T00:00:00,CLE vs. MIN,L,48.0,40,...,24,22,5,19,34,13,27,2,5,26
24,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200182,2022-11-11T00:00:00,CLE @ GSW,L,48.0,37,...,12,10,12,19,21,8,10,4,31,26
25,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200171,2022-11-09T00:00:00,CLE @ SAC,L,48.0,46,...,20,16,27,32,34,13,30,22,8,28
26,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200158,2022-11-07T00:00:00,CLE @ LAC,L,48.0,43,...,5,5,24,19,29,2,24,25,10,24
27,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200140,2022-11-06T00:00:00,CLE @ LAL,W,48.0,37,...,5,31,18,10,5,13,18,6,14,8
28,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200120,2022-11-04T00:00:00,CLE @ DET,W,48.0,44,...,10,4,29,27,1,25,7,16,21,4
29,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200107,2022-11-02T00:00:00,CLE vs. BOS,W,53.0,42,...,1,16,9,19,13,35,30,11,14,21
30,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200090,2022-10-30T00:00:00,CLE vs. NYK,W,48.0,41,...,17,1,18,35,7,2,27,9,7,10
31,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200072,2022-10-28T00:00:00,CLE @ BOS,W,53.0,45,...,20,33,23,27,29,2,36,4,1,16
32,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200056,2022-10-26T00:00:00,CLE vs. ORL,W,48.0,36,...,17,10,12,19,21,25,27,3,28,12
33,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200039,2022-10-23T00:00:00,CLE vs. WAS,W,53.0,41,...,5,31,12,2,7,13,18,11,10,14
34,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200032,2022-10-22T00:00:00,CLE @ CHI,W,48.0,48,...,5,2,27,32,7,33,10,25,3,1
35,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,L,48.0,38,...,28,10,24,27,7,13,24,14,26,25

In [10]:
cavs_games_df.columns

Index(['SEASON_YEAR', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK',
       'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK',
       'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK',
       'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK',
       'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK'],
      dtype='object')

In [14]:
cavs_games_filtered = cavs_games_df[[
    'SEASON_YEAR',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'TEAM_NAME',
    'GAME_ID',
    'WL',
    'FGM',
    'FTM',
    'AST',
    'DREB',
    'STL',
    'BLK'
]]
cavs_games_filtered['GAME_BUCKETS'] = cavs_games_filtered['FGM'] + cavs_games_filtered['FTM'] + cavs_games_filtered['AST']
cavs_games_filtered['GAME_STOPS'] = cavs_games_filtered['DREB'] + cavs_games_filtered['STL'] + cavs_games_filtered['BLK']
cavs_games_filtered.drop(['FGM', 'FTM', 'AST', 'DREB', 'STL', 'BLK'], axis = 1, inplace = True)

/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_944/155881481.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_games_filtered['GAME_BUCKETS'] = cavs_games_filtered['FGM'] + cavs_games_filtered['FTM'] + cavs_games_filtered['AST']
/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_944/155881481.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_games_filtered['GAME_STOPS'] = cavs_games_filtered['DREB'] + cavs_games_filtered['STL'] + cavs_games_filtered['BLK']
/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_944/155881481.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_games_filtered.drop(['FGM', 'FTM', 'AST', 'DREB', 'STL', 'BLK'], axis = 1, inplace = True)

In [15]:
cavs_games_filtered

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,WL,GAME_BUCKETS,GAME_STOPS
0,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200524,L,93,38
1,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200498,L,86,34
2,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200484,L,84,42
3,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200466,W,85,39
4,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200452,W,88,50
5,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200440,W,76,53
6,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200431,W,89,36
7,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200421,W,82,45
8,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200406,L,82,43
9,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200390,W,83,46
10,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200381,L,71,39
11,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200360,W,86,49
12,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200348,L,61,44
13,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200330,W,72,40
14,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200312,W,81,47
15,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200303,L,68,44
16,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200295,W,75,38
17,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200280,L,68,42
18,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200261,W,83,36
19,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200248,W,86,45
20,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200244,W,87,44
21,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200225,W,100,59
22,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200216,L,72,42
23,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200193,L,89,31
24,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200182,L,81,41
25,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200171,L,87,35
26,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200158,L,87,46
27,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200140,W,88,52
28,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200120,W,87,55
29,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200107,W,85,52
30,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200090,W,90,41
31,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200072,W,89,40
32,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200056,W,82,40
33,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200039,W,82,47
34,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200032,W,96,49
35,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200008,L,82,42

In [9]:
cavs_player_games = playergamelogs.PlayerGameLogs(
    team_id_nullable = '1610612739',
    season_nullable = '2022-23'
)
cavs_player_games_df = cavs_player_games.get_data_frames()[0]
cavs_player_games_df

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,VIDEO_AVAILABLE_FLAG
0,2022-23,1628386,Jarrett Allen,Jarrett,1610612739,CLE,Cleveland Cavaliers,0022200524,2022-12-29T00:00:00,CLE @ IND,...,1,157,81,67,180,41,1,1,48,1
1,2022-23,1630596,Evan Mobley,Evan,1610612739,CLE,Cleveland Cavaliers,0022200524,2022-12-29T00:00:00,CLE @ IND,...,326,157,131,123,351,57,43,1,77,1
2,2022-23,1627747,Caris LeVert,Caris,1610612739,CLE,Cleveland Cavaliers,0022200524,2022-12-29T00:00:00,CLE @ IND,...,352,342,46,67,286,102,43,1,94,1
3,2022-23,1629636,Darius Garland,Darius,1610612739,CLE,Cleveland Cavaliers,0022200524,2022-12-29T00:00:00,CLE @ IND,...,1,63,81,74,321,106,43,1,105,1
4,2022-23,201567,Kevin Love,Kevin,1610612739,CLE,Cleveland Cavaliers,0022200524,2022-12-29T00:00:00,CLE @ IND,...,1,301,265,134,194,161,43,1,151,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,2022-23,1629731,Dean Wade,Dean,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,...,1,63,199,184,317,195,43,1,198,1
353,2022-23,1629636,Darius Garland,Darius,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,...,237,63,131,250,309,227,43,1,218,1
354,2022-23,203526,Raul Neto,Raul,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,...,1,1,265,314,286,338,43,1,334,1
355,2022-23,1630171,Isaac Okoro,Isaac,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,...,1,301,265,314,194,355,43,1,341,1
356,2022-23,1628378,Donovan Mitchell,Donovan,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,...,1,301,46,19,82,17,43,1,18,1

In [13]:
cavs_player_games_df.columns

Index(['SEASON_YEAR', 'PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP',
       'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM',
       'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK',
       'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS', 'DD2',
       'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK',
       'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK',
       'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK',
       'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK',
       'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK',
       'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK',
       'WNBA_FANTASY_PTS_RANK', 'VIDEO_AVAILABLE_FLAG'],
      dtype='object')

In [22]:
cavs_player_games_filtered = cavs_player_games_df[[
    'PLAYER_ID',
    'PLAYER_NAME',
    'TEAM_ID',
    'GAME_ID',
    'MIN',
    'FGM',
    'FTM',
    'AST',
    'DREB',
    'STL',
    'BLK'
]]
cavs_player_games_filtered['PLAYER_BUCKETS'] = cavs_player_games_filtered['FGM'] + cavs_player_games_filtered['FTM'] + cavs_player_games_filtered['AST']
cavs_player_games_filtered['PLAYER_STOPS'] = cavs_player_games_filtered['DREB'] + cavs_player_games_filtered['STL'] + cavs_player_games_filtered['BLK']
cavs_player_games_filtered.drop(['FGM', 'FTM', 'AST', 'DREB', 'STL', 'BLK'], axis = 1, inplace = True)

/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_944/2164982249.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_player_games_filtered['PLAYER_BUCKETS'] = cavs_player_games_filtered['FGM'] + cavs_player_games_filtered['FTM'] + cavs_player_games_filtered['AST']
/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_944/2164982249.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_player_games_filtered['PLAYER_STOPS'] = cavs_player_games_filtered['DREB'] + cavs_player_games_filtered['STL'] + cavs_player_games_filtered['BLK']
/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_944/2164982249.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_player_games_filtered.drop(['FGM', 'FTM', 'AST', 'DREB', 'STL', 'BLK'], axis = 1, inplace = True)

In [23]:
cavs_player_games_filtered

,PLAYER_ID,PLAYER_NAME,TEAM_ID,GAME_ID,MIN,PLAYER_BUCKETS,PLAYER_STOPS
0,1628386,Jarrett Allen,1610612739,0022200524,37.566667,12,12
1,1630596,Evan Mobley,1610612739,0022200524,31.933333,15,5
2,1627747,Caris LeVert,1610612739,0022200524,34.850000,12,5
3,1629636,Darius Garland,1610612739,0022200524,35.306667,16,0
4,201567,Kevin Love,1610612739,0022200524,21.073333,6,5
...,...,...,...,...,...,...,...
352,1629731,Dean Wade,1610612739,0022200008,21.693333,6,3
353,1629636,Darius Garland,1610612739,0022200008,13.300000,5,4
354,203526,Raul Neto,1610612739,0022200008,6.033333,0,1
355,1630171,Isaac Okoro,1610612739,0022200008,11.760000,0,0
356,1628378,Donovan Mitchell,1610612739,0022200008,34.523333,26,4

In [40]:
cavs_merged_df = pd.merge(
    cavs_player_games_filtered,
    cavs_games_filtered,
    how = 'inner',
    on = ['TEAM_ID', 'GAME_ID']
)
cavs_merged_df

,PLAYER_ID,PLAYER_NAME,TEAM_ID,GAME_ID,MIN,PLAYER_BUCKETS,PLAYER_STOPS,SEASON_YEAR,TEAM_ABBREVIATION,TEAM_NAME,WL,GAME_BUCKETS,GAME_STOPS
0,1628386,Jarrett Allen,1610612739,0022200524,37.566667,12,12,2022-23,CLE,Cleveland Cavaliers,L,93,38
1,1630596,Evan Mobley,1610612739,0022200524,31.933333,15,5,2022-23,CLE,Cleveland Cavaliers,L,93,38
2,1627747,Caris LeVert,1610612739,0022200524,34.850000,12,5,2022-23,CLE,Cleveland Cavaliers,L,93,38
3,1629636,Darius Garland,1610612739,0022200524,35.306667,16,0,2022-23,CLE,Cleveland Cavaliers,L,93,38
4,201567,Kevin Love,1610612739,0022200524,21.073333,6,5,2022-23,CLE,Cleveland Cavaliers,L,93,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,1629731,Dean Wade,1610612739,0022200008,21.693333,6,3,2022-23,CLE,Cleveland Cavaliers,L,82,42
353,1629636,Darius Garland,1610612739,0022200008,13.300000,5,4,2022-23,CLE,Cleveland Cavaliers,L,82,42
354,203526,Raul Neto,1610612739,0022200008,6.033333,0,1,2022-23,CLE,Cleveland Cavaliers,L,82,42
355,1630171,Isaac Okoro,1610612739,0022200008,11.760000,0,0,2022-23,CLE,Cleveland Cavaliers,L,82,42
356,1628378,Donovan Mitchell,1610612739,0022200008,34.523333,26,4,2022-23,CLE,Cleveland Cavaliers,L,82,42

In [41]:
cavs_merged_df['BUCKET_CONTRIBUTION'] = cavs_merged_df['PLAYER_BUCKETS'] / cavs_merged_df['GAME_BUCKETS']
cavs_merged_df['STOP_CONTRIBUTION'] = cavs_merged_df['PLAYER_STOPS'] / cavs_merged_df['GAME_STOPS']
cavs_merged_df['BUCKET_CONTRIBUTION_RATE'] = cavs_merged_df['BUCKET_CONTRIBUTION'] * 100
cavs_merged_df['STOP_CONTRIBUTION_RATE'] = cavs_merged_df['STOP_CONTRIBUTION'] * 100

In [42]:
cavs_merged_df

,PLAYER_ID,PLAYER_NAME,TEAM_ID,GAME_ID,MIN,PLAYER_BUCKETS,PLAYER_STOPS,SEASON_YEAR,TEAM_ABBREVIATION,TEAM_NAME,WL,GAME_BUCKETS,GAME_STOPS,BUCKET_CONTRIBUTION,STOP_CONTRIBUTION,BUCKET_CONTRIBUTION_RATE,STOP_CONTRIBUTION_RATE
0,1628386,Jarrett Allen,1610612739,0022200524,37.566667,12,12,2022-23,CLE,Cleveland Cavaliers,L,93,38,0.129032,0.315789,12.903226,31.578947
1,1630596,Evan Mobley,1610612739,0022200524,31.933333,15,5,2022-23,CLE,Cleveland Cavaliers,L,93,38,0.161290,0.131579,16.129032,13.157895
2,1627747,Caris LeVert,1610612739,0022200524,34.850000,12,5,2022-23,CLE,Cleveland Cavaliers,L,93,38,0.129032,0.131579,12.903226,13.157895
3,1629636,Darius Garland,1610612739,0022200524,35.306667,16,0,2022-23,CLE,Cleveland Cavaliers,L,93,38,0.172043,0.000000,17.204301,0.000000
4,201567,Kevin Love,1610612739,0022200524,21.073333,6,5,2022-23,CLE,Cleveland Cavaliers,L,93,38,0.064516,0.131579,6.451613,13.157895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,1629731,Dean Wade,1610612739,0022200008,21.693333,6,3,2022-23,CLE,Cleveland Cavaliers,L,82,42,0.073171,0.071429,7.317073,7.142857
353,1629636,Darius Garland,1610612739,0022200008,13.300000,5,4,2022-23,CLE,Cleveland Cavaliers,L,82,42,0.060976,0.095238,6.097561,9.523810
354,203526,Raul Neto,1610612739,0022200008,6.033333,0,1,2022-23,CLE,Cleveland Cavaliers,L,82,42,0.000000,0.023810,0.000000,2.380952
355,1630171,Isaac Okoro,1610612739,0022200008,11.760000,0,0,2022-23,CLE,Cleveland Cavaliers,L,82,42,0.000000,0.000000,0.000000,0.000000
356,1628378,Donovan Mitchell,1610612739,0022200008,34.523333,26,4,2022-23,CLE,Cleveland Cavaliers,L,82,42,0.317073,0.095238,31.707317,9.523810

In [31]:
cavs_players_list = cavs_merged_df['PLAYER_ID'].unique().tolist()
cavs_stats_dfs = []
for player_id in cavs_players_list:
    player_season_stats_df = playercareerstats.PlayerCareerStats(
        player_id = player_id,
        per_mode36 = 'PerGame'
    ).get_data_frames()[0]
    cavs_stats_dfs.append(player_season_stats_df)

all_cavs_stats_dfs = pd.concat(cavs_stats_dfs)
all_cavs_stats_dfs

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1628386,2017-18,00,1610612751,BKN,20.0,72,31,20.0,3.3,...,0.776,2.0,3.4,5.4,0.7,0.4,1.2,1.1,2.0,8.2
1,1628386,2018-19,00,1610612751,BKN,21.0,80,80,26.2,4.2,...,0.709,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9
2,1628386,2019-20,00,1610612751,BKN,22.0,70,64,26.5,4.3,...,0.633,3.1,6.5,9.6,1.6,0.6,1.3,1.1,2.3,11.1
3,1628386,2020-21,00,1610612751,BKN,23.0,12,5,26.6,3.7,...,0.754,3.2,7.3,10.4,1.7,0.6,1.6,1.8,1.8,11.2
4,1628386,2020-21,00,1610612739,CLE,23.0,51,40,30.3,5.0,...,0.690,3.1,6.8,9.9,1.7,0.5,1.4,1.5,1.5,13.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,1629603,2022-23,00,1610612739,CLE,25.0,11,2,7.5,0.9,...,0.000,0.3,0.7,1.0,0.2,0.2,0.5,0.5,1.0,2.2
0,1629731,2019-20,00,1610612739,CLE,23.0,12,0,6.0,0.8,...,0.000,0.3,1.3,1.6,0.2,0.2,0.3,0.3,0.7,1.7
1,1629731,2020-21,00,1610612739,CLE,24.0,63,19,19.2,2.1,...,0.769,0.6,2.8,3.4,1.2,0.6,0.3,0.5,1.2,6.0
2,1629731,2021-22,00,1610612739,CLE,25.0,51,28,19.2,1.9,...,0.667,0.6,2.3,2.9,1.0,0.6,0.1,0.3,1.7,5.3
3,1629731,2022-23,00,1610612739,CLE,26.0,17,9,24.1,2.2,...,0.692,0.6,3.5,4.1,1.0,0.7,0.4,0.4,2.5,6.4

In [34]:
all_cavs_stats_dfs['AVERAGE_BUCKETS'] = all_cavs_stats_dfs['FGM'] + all_cavs_stats_dfs['FTM'] + all_cavs_stats_dfs['AST']
all_cavs_stats_dfs['AVERAGE_STOPS'] = all_cavs_stats_dfs['DREB'] + all_cavs_stats_dfs['STL'] + all_cavs_stats_dfs['BLK']

In [36]:
cavs_career_stats = all_cavs_stats_dfs[[
    'PLAYER_ID',
    'SEASON_ID',
    'TEAM_ID',
    'AVERAGE_BUCKETS',
    'AVERAGE_STOPS'
]]
cavs_career_stats.rename(columns = {'SEASON_ID': 'SEASON_YEAR'}, inplace = True)
cavs_career_stats

/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_944/3132321427.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_career_stats.rename(columns = {'SEASON_ID': 'SEASON_YEAR'}, inplace = True)

    PLAYER_ID SEASON_YEAR     TEAM_ID  AVERAGE_BUCKETS  AVERAGE_STOPS
0     1628386     2017-18  1610612751              5.6            5.0
1     1628386     2018-19  1610612751              8.1            8.0
2     1628386     2019-20  1610612751              8.3            8.4
3     1628386     2020-21  1610612751              9.2            9.5
4     1628386     2020-21  1610612739              9.8            8.7
..        ...         ...         ...              ...            ...
2     1629603     2022-23  1610612739              1.1            1.4
0     1629731     2019-20  1610612739              1.0            1.8
1     1629731     2020-21  1610612739              3.8            3.7
2     1629731     2021-22  1610612739              3.3            3.0
3     1629731     2022-23  1610612739              3.7            4.6

[89 rows x 5 columns]

In [43]:
cavs_merged_df_2 = pd.merge(
    cavs_merged_df,
    cavs_career_stats,
    how = 'inner',
    on = ['PLAYER_ID', 'TEAM_ID', 'SEASON_YEAR']
)
cavs_merged_df_2['BUCKET_UPLIFT'] = (cavs_merged_df_2['PLAYER_BUCKETS'] - cavs_merged_df_2['AVERAGE_BUCKETS']) / cavs_merged_df_2['AVERAGE_BUCKETS']
cavs_merged_df_2['STOP_UPLIFT'] = (cavs_merged_df_2['PLAYER_STOPS'] - cavs_merged_df_2['AVERAGE_STOPS']) / cavs_merged_df_2['AVERAGE_STOPS']
cavs_merged_df_2

,PLAYER_ID,PLAYER_NAME,TEAM_ID,GAME_ID,MIN,PLAYER_BUCKETS,PLAYER_STOPS,SEASON_YEAR,TEAM_ABBREVIATION,TEAM_NAME,...,GAME_BUCKETS,GAME_STOPS,BUCKET_CONTRIBUTION,STOP_CONTRIBUTION,BUCKET_CONTRIBUTION_RATE,STOP_CONTRIBUTION_RATE,AVERAGE_BUCKETS,AVERAGE_STOPS,BUCKET_UPLIFT,STOP_UPLIFT
0,1628386,Jarrett Allen,1610612739,0022200524,37.566667,12,12,2022-23,CLE,Cleveland Cavaliers,...,93,38,0.129032,0.315789,12.903226,31.578947,9.9,9.2,0.212121,0.304348
1,1628386,Jarrett Allen,1610612739,0022200498,31.983333,9,9,2022-23,CLE,Cleveland Cavaliers,...,86,34,0.104651,0.264706,10.465116,26.470588,9.9,9.2,-0.090909,-0.021739
2,1628386,Jarrett Allen,1610612739,0022200484,30.533333,7,7,2022-23,CLE,Cleveland Cavaliers,...,84,42,0.083333,0.166667,8.333333,16.666667,9.9,9.2,-0.292929,-0.239130
3,1628386,Jarrett Allen,1610612739,0022200466,39.766667,14,5,2022-23,CLE,Cleveland Cavaliers,...,85,39,0.164706,0.128205,16.470588,12.820513,9.9,9.2,0.414141,-0.456522
4,1628386,Jarrett Allen,1610612739,0022200452,30.095000,15,14,2022-23,CLE,Cleveland Cavaliers,...,88,50,0.170455,0.280000,17.045455,28.000000,9.9,9.2,0.515152,0.521739
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,1629731,Dean Wade,1610612739,0022200072,38.928333,3,6,2022-23,CLE,Cleveland Cavaliers,...,89,40,0.033708,0.150000,3.370787,15.000000,3.7,4.6,-0.189189,0.304348
353,1629731,Dean Wade,1610612739,0022200056,29.725000,4,4,2022-23,CLE,Cleveland Cavaliers,...,82,40,0.048780,0.100000,4.878049,10.000000,3.7,4.6,0.081081,-0.130435
354,1629731,Dean Wade,1610612739,0022200039,21.315000,9,3,2022-23,CLE,Cleveland Cavaliers,...,82,47,0.109756,0.063830,10.975610,6.382979,3.7,4.6,1.432432,-0.347826
355,1629731,Dean Wade,1610612739,0022200032,4.116667,3,2,2022-23,CLE,Cleveland Cavaliers,...,96,49,0.031250,0.040816,3.125000,4.081633,3.7,4.6,-0.189189,-0.565217
356,1629731,Dean Wade,1610612739,0022200008,21.693333,6,3,2022-23,CLE,Cleveland Cavaliers,...,82,42,0.073171,0.071429,7.317073,7.142857,3.7,4.6,0.621622,-0.347826

In [45]:
cavs_team_game_averages = cavs_merged_df_2[['TEAM_ID', 'GAME_ID', 'BUCKET_UPLIFT', 'STOP_UPLIFT']]
cavs_team_game_averages = cavs_team_game_averages.groupby(['TEAM_ID', 'GAME_ID']).mean().reset_index()
cavs_team_game_averages.rename(columns = {'BUCKET_UPLIFT': 'AVG_BUCKET_UPLIFT', 'STOP_UPLIFT': 'AVG_STOP_UPLIFT'}, inplace = True)
cavs_team_game_averages

       TEAM_ID     GAME_ID  AVG_BUCKET_UPLIFT  AVG_STOP_UPLIFT
0   1610612739  0022200008          -0.149716        -0.149502
1   1610612739  0022200032           0.357974         0.384216
2   1610612739  0022200039           0.144229         0.136635
3   1610612739  0022200056           0.178816        -0.179621
4   1610612739  0022200072           0.000116        -0.252644
5   1610612739  0022200090           0.026274        -0.264390
6   1610612739  0022200107          -0.233732         0.017180
7   1610612739  0022200120           0.427294         0.569865
8   1610612739  0022200140          -0.094944        -0.112377
9   1610612739  0022200158          -0.012991        -0.151573
10  1610612739  0022200171          -0.164112        -0.356629
11  1610612739  0022200182          -0.144202        -0.062530
12  1610612739  0022200193           0.208876        -0.124537
13  1610612739  0022200216          -0.107353         0.048539
14  1610612739  0022200225          -0.107703         0.109510
15  1610612739  0022200244           0.045338         0.018057
16  1610612739  0022200248           0.065366         0.112841
17  1610612739  0022200261          -0.233749        -0.324893
18  1610612739  0022200280           0.334732        -0.154232
19  1610612739  0022200295          -0.066679         0.148425
20  1610612739  0022200303           0.279732         0.244679
21  1610612739  0022200312           0.287935         0.380867
22  1610612739  0022200330          -0.317527        -0.268736
23  1610612739  0022200348          -0.404889         0.002858
24  1610612739  0022200360          -0.348344        -0.119389
25  1610612739  0022200381           0.044453         0.212500
26  1610612739  0022200390           0.305258         0.440128
27  1610612739  0022200406          -0.248811         0.020834
28  1610612739  0022200421          -0.249102        -0.135451
29  1610612739  0022200431          -0.127385        -0.186103
30  1610612739  0022200440          -0.197043         0.299231
31  1610612739  0022200452           0.047658         0.386538
32  1610612739  0022200466           0.015598        -0.001850
33  1610612739  0022200484           0.080667        -0.099736
34  1610612739  0022200498          -0.151631        -0.370927
35  1610612739  0022200524           0.242198        -0.148448

In [47]:
cavs_merged_df_3 = pd.merge(
    cavs_merged_df_2,
    cavs_team_game_averages,
    how = 'inner',
    on = ['TEAM_ID', 'GAME_ID']
)
cavs_merged_df_3['TEAM_BUCKET_UPLIFT_CONT_RATE'] = cavs_merged_df_3['BUCKET_CONTRIBUTION'] * cavs_merged_df_3['AVG_BUCKET_UPLIFT'] * 100
cavs_merged_df_3['TEAM_STOP_UPLIFT_CONT_RATE'] = cavs_merged_df_3['STOP_CONTRIBUTION'] * cavs_merged_df_3['AVG_STOP_UPLIFT'] * 100
cavs_merged_df_3

,PLAYER_ID,PLAYER_NAME,TEAM_ID,GAME_ID,MIN,PLAYER_BUCKETS,PLAYER_STOPS,SEASON_YEAR,TEAM_ABBREVIATION,TEAM_NAME,...,BUCKET_CONTRIBUTION_RATE,STOP_CONTRIBUTION_RATE,AVERAGE_BUCKETS,AVERAGE_STOPS,BUCKET_UPLIFT,STOP_UPLIFT,AVG_BUCKET_UPLIFT,AVG_STOP_UPLIFT,TEAM_BUCKET_UPLIFT_CONT_RATE,TEAM_STOP_UPLIFT_CONT_RATE
0,1628386,Jarrett Allen,1610612739,0022200524,37.566667,12,12,2022-23,CLE,Cleveland Cavaliers,...,12.903226,31.578947,9.9,9.2,0.212121,0.304348,0.242198,-0.148448,3.125135,-4.687831
1,1630596,Evan Mobley,1610612739,0022200524,31.933333,15,5,2022-23,CLE,Cleveland Cavaliers,...,16.129032,13.157895,11.3,8.5,0.327434,-0.411765,0.242198,-0.148448,3.906418,-1.953263
2,1627747,Caris LeVert,1610612739,0022200524,34.850000,12,5,2022-23,CLE,Cleveland Cavaliers,...,12.903226,13.157895,9.9,4.3,0.212121,0.162791,0.242198,-0.148448,3.125135,-1.953263
3,1629636,Darius Garland,1610612739,0022200524,35.306667,16,0,2022-23,CLE,Cleveland Cavaliers,...,17.204301,0.000000,19.4,3.7,-0.175258,-1.000000,0.242198,-0.148448,4.166846,-0.000000
4,201567,Kevin Love,1610612739,0022200524,21.073333,6,5,2022-23,CLE,Cleveland Cavaliers,...,6.451613,13.157895,6.5,6.4,-0.076923,-0.218750,0.242198,-0.148448,1.562567,-1.953263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,1630171,Isaac Okoro,1610612739,0022200193,28.833333,5,2,2022-23,CLE,Cleveland Cavaliers,...,5.617978,6.451613,3.5,2.6,0.428571,-0.230769,0.208876,-0.124537,1.173461,-0.803466
353,1626224,Cedi Osman,1610612739,0022200193,27.686667,10,4,2022-23,CLE,Cleveland Cavaliers,...,11.235955,12.903226,6.3,2.9,0.587302,0.379310,0.208876,-0.124537,2.346922,-1.606932
354,201577,Robin Lopez,1610612739,0022200193,16.241667,3,2,2022-23,CLE,Cleveland Cavaliers,...,3.370787,6.451613,2.1,0.8,0.428571,1.500000,0.208876,-0.124537,0.704077,-0.803466
355,203526,Raul Neto,1610612739,0022200193,5.408333,0,0,2022-23,CLE,Cleveland Cavaliers,...,0.000000,0.000000,2.6,1.1,-1.000000,-1.000000,0.208876,-0.124537,0.000000,-0.000000
356,1629603,Mamadi Diakite,1610612739,0022200193,2.558333,0,0,2022-23,CLE,Cleveland Cavaliers,...,0.000000,0.000000,1.1,1.4,-1.000000,-1.000000,0.208876,-0.124537,0.000000,-0.000000

In [48]:
cavs_merged_df_3.columns

Index(['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'GAME_ID', 'MIN',
       'PLAYER_BUCKETS', 'PLAYER_STOPS', 'SEASON_YEAR', 'TEAM_ABBREVIATION',
       'TEAM_NAME', 'WL', 'GAME_BUCKETS', 'GAME_STOPS', 'BUCKET_CONTRIBUTION',
       'STOP_CONTRIBUTION', 'BUCKET_CONTRIBUTION_RATE',
       'STOP_CONTRIBUTION_RATE', 'AVERAGE_BUCKETS', 'AVERAGE_STOPS',
       'BUCKET_UPLIFT', 'STOP_UPLIFT', 'AVG_BUCKET_UPLIFT', 'AVG_STOP_UPLIFT',
       'TEAM_BUCKET_UPLIFT_CONT_RATE', 'TEAM_STOP_UPLIFT_CONT_RATE'],
      dtype='object')

In [49]:
cavs_agg_df = cavs_merged_df_3[[
    'SEASON_YEAR', 
    'PLAYER_ID', 
    'PLAYER_NAME', 
    'TEAM_ID', 
    'TEAM_ABBREVIATION', 
    'TEAM_NAME',
    'MIN',
    'BUCKET_CONTRIBUTION_RATE',
    'STOP_CONTRIBUTION_RATE',
    'TEAM_BUCKET_UPLIFT_CONT_RATE',
    'TEAM_STOP_UPLIFT_CONT_RATE'
]]
cavs_agg_df = cavs_agg_df.groupby(['SEASON_YEAR', 'PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME']).mean().reset_index()

In [50]:
cavs_agg_df

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,MIN,BUCKET_CONTRIBUTION_RATE,STOP_CONTRIBUTION_RATE,TEAM_BUCKET_UPLIFT_CONT_RATE,TEAM_STOP_UPLIFT_CONT_RATE
0,2022-23,201567,Kevin Love,1610612739,CLE,Cleveland Cavaliers,19.868929,7.626389,14.633254,0.097793,-0.577864
1,2022-23,201577,Robin Lopez,1610612739,CLE,Cleveland Cavaliers,8.799924,2.610097,1.968979,0.494790,0.288772
2,2022-23,203526,Raul Neto,1610612739,CLE,Cleveland Cavaliers,8.936212,3.081954,2.262581,0.621488,0.701621
3,2022-23,1626224,Cedi Osman,1610612739,CLE,Cleveland Cavaliers,22.868235,7.526751,6.971676,0.273580,0.201292
4,2022-23,1627747,Caris LeVert,1610612739,CLE,Cleveland Cavaliers,30.453073,11.828299,9.905090,0.231637,-0.015815
5,2022-23,1628378,Donovan Mitchell,1610612739,CLE,Cleveland Cavaliers,36.309323,23.076090,10.730245,-1.281312,-0.384838
6,2022-23,1628386,Jarrett Allen,1610612739,CLE,Cleveland Cavaliers,33.488678,11.606425,20.732040,-0.215328,-0.668042
7,2022-23,1629603,Mamadi Diakite,1610612739,CLE,Cleveland Cavaliers,7.515606,1.420249,3.016552,0.224877,0.685317
8,2022-23,1629636,Darius Garland,1610612739,CLE,Cleveland Cavaliers,35.928778,23.597243,8.328161,-1.124049,0.275460
9,2022-23,1629731,Dean Wade,1610612739,CLE,Cleveland Cavaliers,24.075490,4.585264,10.393653,0.405882,-0.122980
10,2022-23,1630171,Isaac Okoro,1610612739,CLE,Cleveland Cavaliers,18.743380,4.272330,6.092044,0.332231,0.407153
11,2022-23,1630205,Lamar Stevens,1610612739,CLE,Cleveland Cavaliers,23.159583,5.047039,9.494805,-0.184428,0.225123
12,2022-23,1630596,Evan Mobley,1610612739,CLE,Cleveland Cavaliers,34.015509,13.616494,19.553971,-0.237642,-0.230292
13,2022-23,1630600,Isaiah Mobley,1610612739,CLE,Cleveland Cavaliers,3.257083,0.671467,3.213255,0.140927,0.261782