In [1]:
import pandas as pd
import numpy as np

from nba_api.stats.static import players
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playercareerstats
from nba_api.stats.endpoints import playergamelogs
from nba_api.stats.endpoints import teamgamelogs

In [5]:
# https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/static/players.md
players.find_players_by_first_name('LeBron')

[{'id': 2544,
  'full_name': 'LeBron James',
  'first_name': 'LeBron',
  'last_name': 'James',
  'is_active': True}]

In [6]:
# Career stats
# https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/playercareerstats.md

lebron_stats = playercareerstats.PlayerCareerStats(player_id = '2544')
lebron_df = lebron_stats.get_data_frames()[0]
lebron_df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,...,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,...,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,...,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,...,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,...,0.712,133,459,592,539,138,81,255,165,2250
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,3054.0,789,...,0.780,106,507,613,587,137,93,241,139,2304
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,2966.0,768,...,0.767,71,483,554,651,125,77,261,119,2258
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,3063.0,758,...,0.759,80,510,590,554,124,50,284,163,2111
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,2326.0,621,...,0.771,94,398,492,387,115,50,213,96,1683
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,2877.0,765,...,0.753,97,513,610,551,129,67,226,110,2036
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,2902.0,767,...,0.750,81,452,533,488,121,26,270,126,2089
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,2493.0,624,...,0.710,51,365,416,511,109,49,272,135,1743
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,2709.0,737,...,0.731,111,454,565,514,104,49,249,143,1920
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,2795.0,736,...,0.674,97,542,639,646,92,44,303,134,1954
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,3026.0,857,...,0.731,97,612,709,747,116,71,347,136,2251
15,2544,2018-19,00,1610612747,LAL,34.0,55,55,1937.0,558,...,0.665,57,408,465,454,72,33,197,94,1505
16,2544,2019-20,00,1610612747,LAL,35.0,67,67,2316.0,643,...,0.693,66,459,525,684,78,36,261,118,1698
17,2544,2020-21,00,1610612747,LAL,36.0,45,45,1504.0,422,...,0.698,29,317,346,350,48,25,168,70,1126
18,2544,2021-22,00,1610612747,LAL,37.0,56,56,2084.0,640,...,0.756,63,396,459,349,73,59,196,121,1695
19,2544,2022-23,00,1610612747,LAL,37.0,23,23,832.0,245,...,0.726,31,163,194,153,27,15,70,42,624

In [17]:
# Player Game Log
# https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/playergamelogs.md

lebron_games = playergamelogs.PlayerGameLogs(
    player_id_nullable = '2544',
    season_nullable = '2017-18'
)
lebron_games_df = lebron_games.get_data_frames()[0]
lebron_games_df

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,VIDEO_AVAILABLE_FLAG
0,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021701220,2018-04-11T00:00:00,CLE vs. NYK,...,33,1,69,81,31,82,53,19,82,1
1,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021701207,2018-04-09T00:00:00,CLE @ NYK,...,33,39,37,45,13,59,1,19,55,1
2,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021701183,2018-04-06T00:00:00,CLE @ PHI,...,79,1,11,2,26,3,1,1,2,1
3,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021701176,2018-04-05T00:00:00,CLE vs. WAS,...,33,39,25,16,16,32,1,19,22,1
4,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021701156,2018-04-03T00:00:00,CLE vs. TOR,...,1,39,4,40,18,64,1,19,61,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021700058,2017-10-25T00:00:00,CLE @ BKN,...,69,15,25,33,51,13,1,1,17,1
78,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021700049,2017-10-24T00:00:00,CLE vs. CHI,...,33,15,25,13,26,20,1,19,19,2
79,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021700028,2017-10-21T00:00:00,CLE vs. ORL,...,1,1,50,63,80,75,53,19,76,1
80,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021700021,2017-10-20T00:00:00,CLE @ MIL,...,1,39,78,55,16,64,53,19,64,1
81,2017-18,2544,LeBron James,LeBron,1610612739,CLE,Cleveland Cavaliers,0021700001,2017-10-17T00:00:00,CLE vs. BOS,...,33,66,37,33,37,17,1,19,19,1

In [18]:
# Team Game Log
# https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/teamgamelogs.md

cavs_games = teamgamelogs.TeamGameLogs(
    team_id_nullable = '1610612739',
    season_nullable = '2017-18'
)
cavs_games_df = cavs_games.get_data_frames()[0]
cavs_games_df

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,2017-18,1610612739,CLE,Cleveland Cavaliers,0021701220,2018-04-11T00:00:00,CLE vs. NYK,L,48.0,37,...,11,79,60,15,45,20,17,28,69,66
1,2017-18,1610612739,CLE,Cleveland Cavaliers,0021701207,2018-04-09T00:00:00,CLE @ NYK,W,48.0,40,...,40,8,16,15,60,71,17,38,12,13
2,2017-18,1610612739,CLE,Cleveland Cavaliers,0021701183,2018-04-06T00:00:00,CLE @ PHI,L,48.0,45,...,46,36,48,47,60,71,52,16,4,51
3,2017-18,1610612739,CLE,Cleveland Cavaliers,0021701176,2018-04-05T00:00:00,CLE vs. WAS,W,48.0,42,...,71,18,60,10,45,71,6,16,22,41
4,2017-18,1610612739,CLE,Cleveland Cavaliers,0021701156,2018-04-03T00:00:00,CLE vs. TOR,W,48.0,38,...,40,71,25,28,11,2,31,16,43,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2017-18,1610612739,CLE,Cleveland Cavaliers,0021700058,2017-10-25T00:00:00,CLE @ BKN,L,48.0,39,...,14,56,81,57,3,20,31,28,50,58
78,2017-18,1610612739,CLE,Cleveland Cavaliers,0021700049,2017-10-24T00:00:00,CLE vs. CHI,W,48.0,43,...,59,10,4,57,45,20,6,38,22,24
79,2017-18,1610612739,CLE,Cleveland Cavaliers,0021700028,2017-10-21T00:00:00,CLE vs. ORL,L,48.0,33,...,31,79,60,67,3,63,6,3,77,77
80,2017-18,1610612739,CLE,Cleveland Cavaliers,0021700021,2017-10-20T00:00:00,CLE @ MIL,W,48.0,44,...,31,24,70,28,45,6,2,69,28,9
81,2017-18,1610612739,CLE,Cleveland Cavaliers,0021700001,2017-10-17T00:00:00,CLE vs. BOS,W,48.0,38,...,7,65,67,77,26,37,75,13,59,43

In [15]:
la_games_df.columns

Index(['SEASON_YEAR', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK',
       'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK',
       'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK',
       'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK',
       'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK'],
      dtype='object')

1. Get teams list and players list (active)
2. Get player career stats
3. Get all team games for specific season
4. Get player stats per game

In [2]:
players_list = players.get_active_players()
players_df = pd.DataFrame(players_list)
players_df.to_csv('players.csv')

In [6]:
players_df

          id         full_name first_name  last_name  is_active
0    1630173  Precious Achiuwa   Precious    Achiuwa       True
1     203500      Steven Adams     Steven      Adams       True
2    1628389       Bam Adebayo        Bam    Adebayo       True
3    1630534      Ochai Agbaji      Ochai     Agbaji       True
4    1630583      Santi Aldama      Santi     Aldama       True
..       ...               ...        ...        ...        ...
577   201152    Thaddeus Young   Thaddeus      Young       True
578  1629027        Trae Young       Trae      Young       True
579  1630209    Omer Yurtseven       Omer  Yurtseven       True
580   203469       Cody Zeller       Cody     Zeller       True
581  1627826       Ivica Zubac      Ivica      Zubac       True

[582 rows x 5 columns]

In [3]:
teams_list = teams.get_teams()
teams_df = pd.DataFrame(teams_list)
teams_df.to_csv('teams.csv')

In [4]:
#players_list[0]
player_dfs = []
for player in players_list[:10]:
    player_id = player['id']
    player_season_stats_df = playercareerstats.PlayerCareerStats(
        player_id = player_id,
        per_mode36 = 'PerGame'
    ).get_data_frames()[0]
    player_season_stats_df['PLAYER_NAME'] = player['full_name']
    player_dfs.append(player_season_stats_df)

all_player_dfs = pd.concat(player_dfs)
all_player_dfs

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLAYER_NAME
0,1630173,2020-21,00,1610612748,MIA,21.0,61,4,12.1,2.0,...,1.2,2.2,3.4,0.5,0.3,0.5,0.7,1.5,5.0,Precious Achiuwa
1,1630173,2021-22,00,1610612761,TOR,22.0,73,28,23.6,3.6,...,2.0,4.5,6.5,1.1,0.5,0.6,1.2,2.1,9.1,Precious Achiuwa
2,1630173,2022-23,00,1610612761,TOR,23.0,12,0,20.4,3.0,...,2.0,5.0,7.0,1.3,0.2,0.6,1.3,1.6,8.8,Precious Achiuwa
0,203500,2013-14,00,1610612760,OKC,20.0,81,20,14.8,1.1,...,1.8,2.3,4.1,0.5,0.5,0.7,0.9,2.5,3.3,Steven Adams
1,203500,2014-15,00,1610612760,OKC,21.0,70,67,25.3,3.1,...,2.8,4.6,7.5,0.9,0.5,1.2,1.4,3.2,7.7,Steven Adams
2,203500,2015-16,00,1610612760,OKC,22.0,80,80,25.2,3.3,...,2.7,3.9,6.7,0.8,0.5,1.1,1.1,2.8,8.0,Steven Adams
3,203500,2016-17,00,1610612760,OKC,23.0,80,80,29.9,4.7,...,3.5,4.2,7.7,1.1,1.1,1.0,1.8,2.4,11.3,Steven Adams
4,203500,2017-18,00,1610612760,OKC,24.0,76,76,32.7,5.9,...,5.1,4.0,9.0,1.2,1.2,1.0,1.7,2.8,13.9,Steven Adams
5,203500,2018-19,00,1610612760,OKC,25.0,80,80,33.4,6.0,...,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9,Steven Adams
6,203500,2019-20,00,1610612760,OKC,26.0,63,63,26.7,4.5,...,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9,Steven Adams
7,203500,2020-21,00,1610612740,NOP,27.0,58,58,27.7,3.3,...,3.7,5.2,8.9,1.9,0.9,0.7,1.3,1.9,7.6,Steven Adams
8,203500,2021-22,00,1610612763,MEM,28.0,76,75,26.3,2.8,...,4.6,5.4,10.0,3.4,0.9,0.8,1.5,2.0,6.9,Steven Adams
9,203500,2022-23,00,1610612763,MEM,29.0,31,31,26.5,3.5,...,4.9,5.6,10.5,2.2,0.8,1.1,1.9,2.3,7.9,Steven Adams
0,1628389,2017-18,00,1610612748,MIA,20.0,69,19,19.8,2.5,...,1.7,3.8,5.5,1.5,0.5,0.6,1.0,2.0,6.9,Bam Adebayo
1,1628389,2018-19,00,1610612748,MIA,21.0,82,28,23.3,3.4,...,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9,Bam Adebayo
2,1628389,2019-20,00,1610612748,MIA,22.0,72,72,33.6,6.1,...,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9,Bam Adebayo
3,1628389,2020-21,00,1610612748,MIA,23.0,64,64,33.5,7.1,...,2.2,6.7,9.0,5.4,1.2,1.0,2.6,2.3,18.7,Bam Adebayo
4,1628389,2021-22,00,1610612748,MIA,24.0,56,56,32.6,7.3,...,2.4,7.6,10.1,3.4,1.4,0.8,2.6,3.1,19.1,Bam Adebayo
5,1628389,2022-23,00,1610612748,MIA,25.0,32,32,35.1,8.3,...,2.6,7.2,9.8,3.2,1.0,0.7,3.1,3.2,20.9,Bam Adebayo
0,1630534,2022-23,00,1610612762,UTA,22.0,16,0,7.9,1.1,...,0.4,0.7,1.1,0.2,0.1,0.0,0.0,0.8,2.7,Ochai Agbaji
0,1630583,2021-22,00,1610612763,MEM,21.0,32,0,11.2,1.7,...,1.0,1.7,2.7,0.7,0.2,0.3,0.5,1.1,4.1,Santi Aldama
1,1630583,2022-23,00,1610612763,MEM,21.0,33,16,23.3,3.4,...,1.2,4.0,5.2,1.3,0.7,0.9,0.6,2.3,9.6,Santi Aldama
0,1629638,2019-20,00,1610612740,NOP,21.0,47,1,12.6,2.1,...,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7,Nickeil Alexander-Walker
1,1629638,2020-21,00,1610612740,NOP,22.0,46,13,21.9,4.2,...,0.3,2.8,3.1,2.2,1.0,0.5,1.5,1.9,11.0,Nickeil Alexander-Walker
2,1629638,2021-22,00,1610612740,NOP,23.0,50,19,26.3,4.7,...,0.7,2.6,3.3,2.8,0.8,0.4,1.7,1.8,12.8,Nickeil Alexander-Walker
3,1629638,2021-22,00,1610612762,UTA,23.0,15,2,9.9,1.1,...,0.1,1.5,1.5,1.1,0.3,0.3,0.5,1.0,3.5,Nickeil Alexander-Walker
4,1629638,2021-22,00,0,TOT,23.0,65,21,22.6,3.9,...,0.6,2.3,2.9,2.4,0.7,0.4,1.4,1.6,10.6,Nickeil Alexander-Walker
5,1629638,2022-23,00,1610612762,UTA,24.0,26,2,15.5,2.5,...,0.3,1.3,1.6,2.3,0.7,0.4,1.3,1.7,6.8,Nickeil Alexander-Walker
0,1628960,2018-19,00,1610612762,UTA,23.0,38,2,11.0,1.8,...,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6,Grayson Allen
1,1628960,2019-20,00,1610612763,MEM,24.0,38,0,18.9,3.1,...,0.2,2.0,2.2,1.4,0.3,0.1,0.9,1.4,8.7,Grayson Allen
2,1628960,2020-21,00,1610612763,MEM,25.0,50,38,25.2,3.5,...,0.4,2.8,3.2,2.2,0.9,0.2,1.0,1.4,10.6,Grayson Allen
3,1628960,2021-22,00,1610612749,MIL,26.0,66,61,27.3,3.9,...,0.5,2.9,3.4,1.5,0.7,0.3,0.7,1.5,11.1,Grayson Allen
4,1628960,2022-23,00,1610612749,MIL,27.0,32,30,27.4,3.3,...,1.0,2.6,3.6,2.4,0.7,0.2,1.1,1.4,10.2,Grayson Allen
0,1628386,2017-18,00,1610612751,BKN,20.0,72,31,20.0,3.3,...,2.0,3.4,5.4,0.7,0.4,1.2,1.1,2.0,8.2,Jarrett Allen
1,1628386,2018-19,00,1610612751,BKN,21.0,80,80,26.2,4.2,...,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9,Jarrett Allen
2,1628386,2019-20,00,1610612751,BKN,22.0,70,64,26.5,4.3,...,3.1,6.5,9.6,1.6,0.6,1.3,1.1,2.3,11.1,Jarrett Allen
3,1628386,2020-21,00,1610612751,BKN,23.0,12,5,26.6,3.7,...,3.2,7.3,10.4,1.7,0.6,1.6,1.8,1.8,11.2,Jarrett Allen
4,1628386,2020-21,00,1610612739,CLE,23.0,51,40,30.3,5.0,...,3.1,6.8,9.9,1.7,0.5,1.4,1.5,1.5,13.2,Jarrett Allen
5,1628386,2020-21,00,0,TOT,23.0,63,45,29.6,4.7,...,3.1,6.9,10.0,1.7,0.5,1.4,1.6,1.5,12.8,Jarrett Allen
6,1628386,2021-22,00,1610612739,CLE,24.0,56,56,32.3,6.6,...,3.4,7.3,10.8,1.6,0.8,1.3,1.7,1.7,16.1,Jarrett Allen
7,1628386,2022-23,00,1610612739,CLE,24.0,29,29,33.5,5.6,...,3.0,7.2,10.2,1.4,0.8,1.2,1.5,2.2,14.0,Jarrett Allen
0,1630631,2021-22,00,1610612740,NOP,24.0,54,1,15.4,2.4,...,0.5,1.4,1.9,2.8,1.3,0.1,0.7,1.4,6.1,Jose Alvarado
1,1630631,2022-23,00,1610612740,NOP,24.0,34,7,20.7,3.3,...,0.5,1.8,2.3,3.0,1.4,0.1,1.4,2.1,9.0,Jose Alvarado
0,203937,2014-15,00,1610612759,SAS,21.0,33,8,10.9,0.9,...,0.2,2.0,2.2,0.8,0.5,0.2,0.3,0.8,2.2,Kyle Anderson
1,203937,2015-16,00,1610612759,SAS,22.0,78,11,16.0,1.8,...,0.3,2.8,3.1,1.6,0.8,0.4,0.8,1.2,4.5,Kyle Anderson
2,203937,2016-17,00,1610612759,SAS,23.0,72,14,14.2,1.3,...,0.5,2.4,2.9,1.3,0.7,0.4,0.5,0.9,3.4,Kyle Anderson
3,203937,2017-18,00,1610612759,SAS,24.0,74,67,26.7,3.1,...,1.1,4.2,5.4,2.7,1.6,0.8,1.3,1.5,7.9,Kyle Anderson
4,203937,2018-19,00,1610612763,MEM,25.0,43,40,29.8,3.5,...,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0,Kyle Anderson
5,203937,2019-20,00,1610612763,MEM,26.0,67,28,19.8,2.3,...,0.9,3.4,4.3,2.4,0.8,0.6,1.0,1.7,5.8,Kyle Anderson
6,203937,2020-21,00,1610612763,MEM,27.0,69,69,27.4,4.5,...,0.8,5.0,5.7,3.6,1.2,0.8,1.2,1.7,12.4,Kyle Anderson
7,203937,2021-22,00,1610612763,MEM,28.0,69,11,21.5,3.0,...,1.0,4.3,5.3,2.7,1.1,0.7,1.0,1.6,7.6,Kyle Anderson
8,203937,2022-23,00,1610612750,MIN,29.0,26,11,24.3,2.7,...,0.5,3.6,4.1,3.4,1.1,0.8,1.4,2.0,7.3,Kyle Anderson

In [5]:
all_player_dfs.columns

Index(['PLAYER_ID', 'SEASON_ID', 'LEAGUE_ID', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS', 'PLAYER_NAME'],
      dtype='object')

In [2]:
cavs_games = teamgamelogs.TeamGameLogs(
    team_id_nullable = '1610612739',
    season_nullable = '2022-23'
)
cavs_games_df = cavs_games.get_data_frames()[0]
cavs_games_df

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200540,2022-12-31T00:00:00,CLE @ CHI,W,48.0,39,...,3,30,36,4,7,25,16,33,28,21
1,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200524,2022-12-29T00:00:00,CLE @ IND,L,48.0,50,...,15,5,9,11,14,35,10,28,4,31
2,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200498,2022-12-26T00:00:00,CLE vs. BKN,L,48.0,39,...,36,27,11,7,22,13,3,9,10,30
3,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200484,2022-12-23T00:00:00,CLE vs. TOR,L,48.0,39,...,33,8,21,4,14,2,10,22,24,32
4,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200466,2022-12-21T00:00:00,CLE vs. MIL,W,48.0,41,...,30,22,5,7,22,22,25,14,14,17
5,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200452,2022-12-19T00:00:00,CLE vs. UTA,W,48.0,43,...,14,16,37,28,14,2,19,16,6,5
6,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200440,2022-12-17T00:00:00,CLE vs. DAL,W,53.0,40,...,1,20,12,20,7,25,35,22,33,21
7,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200431,2022-12-16T00:00:00,CLE vs. IND,W,48.0,38,...,34,20,5,20,30,13,7,16,9,20
8,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200421,2022-12-14T00:00:00,CLE @ DAL,W,48.0,41,...,18,9,3,28,30,8,19,33,26,7
9,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200406,2022-12-12T00:00:00,CLE @ SAS,L,48.0,45,...,15,27,21,11,3,2,1,25,22,24
10,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200390,2022-12-10T00:00:00,CLE vs. OKC,W,48.0,40,...,6,10,12,20,14,25,3,6,23,17
11,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200381,2022-12-09T00:00:00,CLE vs. SAC,L,48.0,34,...,32,30,32,11,14,22,31,16,35,32
12,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200360,2022-12-06T00:00:00,CLE vs. LAL,W,48.0,48,...,15,10,1,1,22,25,19,35,13,8
13,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200348,2022-12-04T00:00:00,CLE @ NYK,L,48.0,29,...,27,35,29,11,5,8,7,30,37,32
14,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200330,2022-12-02T00:00:00,CLE vs. ORL,W,48.0,41,...,36,22,12,11,7,13,3,35,24,12
15,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200312,2022-11-30T00:00:00,CLE vs. PHI,W,48.0,45,...,25,7,29,2,22,1,1,37,19,2
16,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200303,2022-11-28T00:00:00,CLE @ TOR,L,48.0,34,...,11,27,5,11,22,22,16,29,36,35
17,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200295,2022-11-27T00:00:00,CLE @ DET,W,48.0,33,...,23,36,18,36,14,25,19,6,30,17
18,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200280,2022-11-25T00:00:00,CLE @ MIL,L,48.0,34,...,23,37,3,4,30,36,10,16,30,36
19,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200261,2022-11-23T00:00:00,CLE vs. POR,W,48.0,41,...,27,22,24,33,14,13,3,11,14,6
20,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200248,2022-11-21T00:00:00,CLE vs. ATL,W,48.0,42,...,30,16,32,7,22,8,10,21,14,11
21,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200244,2022-11-20T00:00:00,CLE vs. MIA,W,48.0,44,...,5,3,32,11,35,8,31,30,19,3
22,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200225,2022-11-18T00:00:00,CLE vs. CHA,W,58.0,49,...,3,10,32,7,2,25,36,1,1,14
23,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200216,2022-11-16T00:00:00,CLE @ MIL,L,48.0,36,...,34,22,1,11,3,25,16,30,34,36
24,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200193,2022-11-13T00:00:00,CLE vs. MIN,L,48.0,40,...,25,22,5,20,35,13,28,2,5,27
25,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200182,2022-11-11T00:00:00,CLE @ GSW,L,48.0,37,...,13,10,12,20,22,8,10,4,32,27
26,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200171,2022-11-09T00:00:00,CLE @ SAC,L,48.0,46,...,21,16,27,33,35,13,31,22,8,29
27,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200158,2022-11-07T00:00:00,CLE @ LAC,L,48.0,43,...,6,5,24,20,30,2,25,25,10,25
28,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200140,2022-11-06T00:00:00,CLE @ LAL,W,48.0,37,...,6,32,18,11,5,13,19,6,14,8
29,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200120,2022-11-04T00:00:00,CLE @ DET,W,48.0,44,...,11,4,29,28,1,25,7,16,21,4
30,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200107,2022-11-02T00:00:00,CLE vs. BOS,W,53.0,42,...,1,16,9,20,14,36,31,11,14,21
31,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200090,2022-10-30T00:00:00,CLE vs. NYK,W,48.0,41,...,18,1,18,36,7,2,28,9,7,10
32,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200072,2022-10-28T00:00:00,CLE @ BOS,W,53.0,45,...,21,34,23,28,30,2,37,4,1,16
33,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200056,2022-10-26T00:00:00,CLE vs. ORL,W,48.0,36,...,18,10,12,20,22,25,28,3,28,12
34,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200039,2022-10-23T00:00:00,CLE vs. WAS,W,53.0,41,...,6,32,12,2,7,13,19,11,10,14
35,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200032,2022-10-22T00:00:00,CLE @ CHI,W,48.0,48,...,6,2,27,33,7,34,10,25,3,1
36,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,L,48.0,38,...,29,10,24,28,7,13,25,14,26,26

In [10]:
cavs_games_df.columns

Index(['SEASON_YEAR', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK',
       'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK',
       'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK',
       'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK',
       'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK'],
      dtype='object')

In [37]:
cavs_games_filtered = cavs_games_df[[
    'SEASON_YEAR',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'TEAM_NAME',
    'GAME_ID',
    'WL',
    'FGM',
    'FTM',
    'AST',
    'DREB',
    'STL',
    'BLK',
    'MIN'
]]
cavs_games_filtered['GAME_BUCKETS'] = cavs_games_filtered['FGM'] + cavs_games_filtered['FTM'] + cavs_games_filtered['AST']
cavs_games_filtered['GAME_STOPS'] = cavs_games_filtered['DREB'] + cavs_games_filtered['STL'] + cavs_games_filtered['BLK']
cavs_games_filtered.drop(['FGM', 'FTM', 'AST', 'DREB', 'STL', 'BLK'], axis = 1, inplace = True)
cavs_games_filtered.rename(columns = {'MIN': 'GAME_MIN'}, inplace = True)

/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_1136/436585269.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_games_filtered['GAME_BUCKETS'] = cavs_games_filtered['FGM'] + cavs_games_filtered['FTM'] + cavs_games_filtered['AST']
/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_1136/436585269.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_games_filtered['GAME_STOPS'] = cavs_games_filtered['DREB'] + cavs_games_filtered['STL'] + cavs_games_filtered['BLK']
/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_1136/436585269.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_games_filtered.drop(['FGM', 'FTM', 'AST', 'DREB', 'STL', 'BLK'], axis = 1, inplace = True)
/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_1136/436585269.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_games_filtered.rename(columns = {'MIN': 'GAME_MIN'}, inplace = True)

In [38]:
cavs_games_filtered

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,WL,GAME_MIN,GAME_BUCKETS,GAME_STOPS
0,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200540,W,48.0,71,49
1,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200524,L,48.0,93,38
2,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200498,L,48.0,86,34
3,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200484,L,48.0,84,42
4,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200466,W,48.0,85,39
5,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200452,W,48.0,88,50
6,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200440,W,53.0,76,53
7,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200431,W,48.0,89,36
8,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200421,W,48.0,82,45
9,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200406,L,48.0,82,43
10,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200390,W,48.0,83,46
11,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200381,L,48.0,71,39
12,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200360,W,48.0,86,49
13,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200348,L,48.0,61,44
14,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200330,W,48.0,72,40
15,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200312,W,48.0,81,47
16,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200303,L,48.0,68,44
17,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200295,W,48.0,75,38
18,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200280,L,48.0,68,42
19,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200261,W,48.0,83,36
20,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200248,W,48.0,86,45
21,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200244,W,48.0,87,44
22,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200225,W,58.0,100,59
23,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200216,L,48.0,72,42
24,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200193,L,48.0,89,31
25,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200182,L,48.0,81,41
26,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200171,L,48.0,87,35
27,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200158,L,48.0,87,46
28,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200140,W,48.0,88,52
29,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200120,W,48.0,87,55
30,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200107,W,53.0,85,52
31,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200090,W,48.0,90,41
32,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200072,W,53.0,89,40
33,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200056,W,48.0,82,40
34,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200039,W,53.0,82,47
35,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200032,W,48.0,96,49
36,2022-23,1610612739,CLE,Cleveland Cavaliers,0022200008,L,48.0,82,42

In [5]:
cavs_player_games = playergamelogs.PlayerGameLogs(
    team_id_nullable = '1610612739',
    season_nullable = '2022-23'
)
cavs_player_games_df = cavs_player_games.get_data_frames()[0]
cavs_player_games_df

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,VIDEO_AVAILABLE_FLAG
0,2022-23,1627747,Caris LeVert,Caris,1610612739,CLE,Cleveland Cavaliers,0022200540,2022-12-31T00:00:00,CLE @ CHI,...,1,64,133,37,185,62,43,1,45,1
1,2022-23,1628378,Donovan Mitchell,Donovan,1610612739,CLE,Cleveland Cavaliers,0022200540,2022-12-31T00:00:00,CLE @ CHI,...,242,252,22,103,307,92,43,1,85,1
2,2022-23,1628386,Jarrett Allen,Jarrett,1610612739,CLE,Cleveland Cavaliers,0022200540,2022-12-31T00:00:00,CLE @ CHI,...,335,64,203,227,247,104,43,1,127,1
3,2022-23,1630171,Isaac Okoro,Isaac,1610612739,CLE,Cleveland Cavaliers,0022200540,2022-12-31T00:00:00,CLE @ CHI,...,242,252,82,152,170,144,43,1,161,1
4,2022-23,1626224,Cedi Osman,Cedi,1610612739,CLE,Cleveland Cavaliers,0022200540,2022-12-31T00:00:00,CLE @ CHI,...,242,310,203,137,89,198,43,1,171,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,2022-23,1629731,Dean Wade,Dean,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,...,1,64,203,190,327,201,43,1,204,1
363,2022-23,1629636,Darius Garland,Darius,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,...,242,64,133,258,319,234,43,1,225,1
364,2022-23,203526,Raul Neto,Raul,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,...,1,1,272,323,294,347,43,1,343,1
365,2022-23,1630171,Isaac Okoro,Isaac,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,...,1,310,272,323,200,365,43,1,350,1
366,2022-23,1628378,Donovan Mitchell,Donovan,1610612739,CLE,Cleveland Cavaliers,0022200008,2022-10-19T00:00:00,CLE @ TOR,...,1,310,47,19,82,17,43,1,18,1

In [13]:
cavs_player_games_df.columns

Index(['SEASON_YEAR', 'PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP',
       'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM',
       'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK',
       'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS', 'DD2',
       'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK',
       'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK',
       'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK',
       'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK',
       'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK',
       'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK',
       'WNBA_FANTASY_PTS_RANK', 'VIDEO_AVAILABLE_FLAG'],
      dtype='object')

In [42]:
cavs_player_games_filtered = cavs_player_games_df[[
    'PLAYER_ID',
    'PLAYER_NAME',
    'TEAM_ID',
    'GAME_ID',
    'FGM',
    'FTM',
    'AST',
    'DREB',
    'STL',
    'BLK',
    'PLUS_MINUS',
    'MIN'
]]
cavs_player_games_filtered['PLAYER_BUCKETS'] = cavs_player_games_filtered['FGM'] + cavs_player_games_filtered['FTM'] + cavs_player_games_filtered['AST']
cavs_player_games_filtered['PLAYER_STOPS'] = cavs_player_games_filtered['DREB'] + cavs_player_games_filtered['STL'] + cavs_player_games_filtered['BLK']
cavs_player_games_filtered.rename(columns = {'MIN': 'PLAYER_MIN'}, inplace = True)
cavs_player_games_filtered.drop(['FGM', 'FTM', 'AST', 'DREB', 'STL', 'BLK'], axis = 1, inplace = True)

/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_1136/3643468067.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_player_games_filtered['PLAYER_BUCKETS'] = cavs_player_games_filtered['FGM'] + cavs_player_games_filtered['FTM'] + cavs_player_games_filtered['AST']
/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_1136/3643468067.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_player_games_filtered['PLAYER_STOPS'] = cavs_player_games_filtered['DREB'] + cavs_player_games_filtered['STL'] + cavs_player_games_filtered['BLK']
/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_1136/3643468067.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_player_games_filtered.rename(columns = {'MIN': 'PLAYER_MIN'}, inplace = True)
/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_1136/3643468067.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_player_games_filtered.drop(['FGM', 'FTM', 'AST', 'DREB', 'STL', 'BLK'], axis = 1, inplace = True)

In [43]:
cavs_player_games_filtered

,PLAYER_ID,PLAYER_NAME,TEAM_ID,GAME_ID,PLUS_MINUS,PLAYER_MIN,PLAYER_BUCKETS,PLAYER_STOPS
0,1627747,Caris LeVert,1610612739,0022200540,1,37.266667,14,6
1,1628378,Donovan Mitchell,1610612739,0022200540,-9,36.826667,16,6
2,1628386,Jarrett Allen,1610612739,0022200540,-3,34.870000,5,10
3,1630171,Isaac Okoro,1610612739,0022200540,2,22.940000,8,6
4,1626224,Cedi Osman,1610612739,0022200540,9,24.530000,7,3
...,...,...,...,...,...,...,...,...
362,1629731,Dean Wade,1610612739,0022200008,-11,21.693333,6,3
363,1629636,Darius Garland,1610612739,0022200008,-10,13.300000,5,4
364,203526,Raul Neto,1610612739,0022200008,-8,6.033333,0,1
365,1630171,Isaac Okoro,1610612739,0022200008,0,11.760000,0,0
366,1628378,Donovan Mitchell,1610612739,0022200008,10,34.523333,26,4

In [44]:
cavs_merged_df = pd.merge(
    cavs_player_games_filtered,
    cavs_games_filtered,
    how = 'inner',
    on = ['TEAM_ID', 'GAME_ID']
)
cavs_merged_df

,PLAYER_ID,PLAYER_NAME,TEAM_ID,GAME_ID,PLUS_MINUS,PLAYER_MIN,PLAYER_BUCKETS,PLAYER_STOPS,SEASON_YEAR,TEAM_ABBREVIATION,TEAM_NAME,WL,GAME_MIN,GAME_BUCKETS,GAME_STOPS
0,1627747,Caris LeVert,1610612739,0022200540,1,37.266667,14,6,2022-23,CLE,Cleveland Cavaliers,W,48.0,71,49
1,1628378,Donovan Mitchell,1610612739,0022200540,-9,36.826667,16,6,2022-23,CLE,Cleveland Cavaliers,W,48.0,71,49
2,1628386,Jarrett Allen,1610612739,0022200540,-3,34.870000,5,10,2022-23,CLE,Cleveland Cavaliers,W,48.0,71,49
3,1630171,Isaac Okoro,1610612739,0022200540,2,22.940000,8,6,2022-23,CLE,Cleveland Cavaliers,W,48.0,71,49
4,1626224,Cedi Osman,1610612739,0022200540,9,24.530000,7,3,2022-23,CLE,Cleveland Cavaliers,W,48.0,71,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,1629731,Dean Wade,1610612739,0022200008,-11,21.693333,6,3,2022-23,CLE,Cleveland Cavaliers,L,48.0,82,42
363,1629636,Darius Garland,1610612739,0022200008,-10,13.300000,5,4,2022-23,CLE,Cleveland Cavaliers,L,48.0,82,42
364,203526,Raul Neto,1610612739,0022200008,-8,6.033333,0,1,2022-23,CLE,Cleveland Cavaliers,L,48.0,82,42
365,1630171,Isaac Okoro,1610612739,0022200008,0,11.760000,0,0,2022-23,CLE,Cleveland Cavaliers,L,48.0,82,42
366,1628378,Donovan Mitchell,1610612739,0022200008,10,34.523333,26,4,2022-23,CLE,Cleveland Cavaliers,L,48.0,82,42

In [45]:
cavs_merged_df['BUCKET_CONTRIBUTION'] = cavs_merged_df['PLAYER_BUCKETS'] / cavs_merged_df['GAME_BUCKETS']
cavs_merged_df['STOP_CONTRIBUTION'] = cavs_merged_df['PLAYER_STOPS'] / cavs_merged_df['GAME_STOPS']
cavs_merged_df['BUCKET_CONTRIBUTION_RATE'] = cavs_merged_df['BUCKET_CONTRIBUTION'] * 100
cavs_merged_df['STOP_CONTRIBUTION_RATE'] = cavs_merged_df['STOP_CONTRIBUTION'] * 100
cavs_merged_df['MIN_PERCENTAGE'] = cavs_merged_df['PLAYER_MIN'] / cavs_merged_df['GAME_MIN']

In [46]:
cavs_merged_df

,PLAYER_ID,PLAYER_NAME,TEAM_ID,GAME_ID,PLUS_MINUS,PLAYER_MIN,PLAYER_BUCKETS,PLAYER_STOPS,SEASON_YEAR,TEAM_ABBREVIATION,TEAM_NAME,WL,GAME_MIN,GAME_BUCKETS,GAME_STOPS,BUCKET_CONTRIBUTION,STOP_CONTRIBUTION,BUCKET_CONTRIBUTION_RATE,STOP_CONTRIBUTION_RATE,MIN_PERCENTAGE
0,1627747,Caris LeVert,1610612739,0022200540,1,37.266667,14,6,2022-23,CLE,Cleveland Cavaliers,W,48.0,71,49,0.197183,0.122449,19.718310,12.244898,0.776389
1,1628378,Donovan Mitchell,1610612739,0022200540,-9,36.826667,16,6,2022-23,CLE,Cleveland Cavaliers,W,48.0,71,49,0.225352,0.122449,22.535211,12.244898,0.767222
2,1628386,Jarrett Allen,1610612739,0022200540,-3,34.870000,5,10,2022-23,CLE,Cleveland Cavaliers,W,48.0,71,49,0.070423,0.204082,7.042254,20.408163,0.726458
3,1630171,Isaac Okoro,1610612739,0022200540,2,22.940000,8,6,2022-23,CLE,Cleveland Cavaliers,W,48.0,71,49,0.112676,0.122449,11.267606,12.244898,0.477917
4,1626224,Cedi Osman,1610612739,0022200540,9,24.530000,7,3,2022-23,CLE,Cleveland Cavaliers,W,48.0,71,49,0.098592,0.061224,9.859155,6.122449,0.511042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,1629731,Dean Wade,1610612739,0022200008,-11,21.693333,6,3,2022-23,CLE,Cleveland Cavaliers,L,48.0,82,42,0.073171,0.071429,7.317073,7.142857,0.451944
363,1629636,Darius Garland,1610612739,0022200008,-10,13.300000,5,4,2022-23,CLE,Cleveland Cavaliers,L,48.0,82,42,0.060976,0.095238,6.097561,9.523810,0.277083
364,203526,Raul Neto,1610612739,0022200008,-8,6.033333,0,1,2022-23,CLE,Cleveland Cavaliers,L,48.0,82,42,0.000000,0.023810,0.000000,2.380952,0.125694
365,1630171,Isaac Okoro,1610612739,0022200008,0,11.760000,0,0,2022-23,CLE,Cleveland Cavaliers,L,48.0,82,42,0.000000,0.000000,0.000000,0.000000,0.245000
366,1628378,Donovan Mitchell,1610612739,0022200008,10,34.523333,26,4,2022-23,CLE,Cleveland Cavaliers,L,48.0,82,42,0.317073,0.095238,31.707317,9.523810,0.719236

In [11]:
cavs_players_list = cavs_merged_df['PLAYER_ID'].unique().tolist()
cavs_stats_dfs = []
for player_id in cavs_players_list:
    player_season_stats_df = playercareerstats.PlayerCareerStats(
        player_id = player_id,
        per_mode36 = 'PerGame'
    ).get_data_frames()[0]
    cavs_stats_dfs.append(player_season_stats_df)

all_cavs_stats_dfs = pd.concat(cavs_stats_dfs)
all_cavs_stats_dfs

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1627747,2016-17,00,1610612751,BKN,22.0,57,26,21.7,3.0,...,0.720,0.4,2.9,3.3,1.9,0.9,0.1,1.0,1.6,8.2
1,1627747,2017-18,00,1610612751,BKN,23.0,71,10,26.2,4.5,...,0.711,0.7,2.9,3.7,4.2,1.2,0.3,2.2,2.2,12.1
2,1627747,2018-19,00,1610612751,BKN,24.0,40,25,26.6,5.2,...,0.691,0.9,2.9,3.8,3.9,1.1,0.4,1.7,1.9,13.7
3,1627747,2019-20,00,1610612751,BKN,25.0,45,31,29.6,6.9,...,0.711,1.1,3.1,4.2,4.4,1.2,0.2,2.6,1.8,18.7
4,1627747,2020-21,00,1610612751,BKN,26.0,12,4,27.8,7.3,...,0.765,0.8,3.5,4.3,6.0,1.1,0.5,2.2,1.7,18.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,1630600,2022-23,00,1610612739,CLE,23.0,8,0,3.3,0.5,...,0.000,0.1,1.3,1.4,0.0,0.1,0.0,0.0,0.3,1.1
0,1629731,2019-20,00,1610612739,CLE,23.0,12,0,6.0,0.8,...,0.000,0.3,1.3,1.6,0.2,0.2,0.3,0.3,0.7,1.7
1,1629731,2020-21,00,1610612739,CLE,24.0,63,19,19.2,2.1,...,0.769,0.6,2.8,3.4,1.2,0.6,0.3,0.5,1.2,6.0
2,1629731,2021-22,00,1610612739,CLE,25.0,51,28,19.2,1.9,...,0.667,0.6,2.3,2.9,1.0,0.6,0.1,0.3,1.7,5.3
3,1629731,2022-23,00,1610612739,CLE,26.0,17,9,24.1,2.2,...,0.692,0.6,3.5,4.1,1.0,0.7,0.4,0.4,2.5,6.4

In [13]:
all_cavs_stats_dfs.to_csv('cavs_stats.csv', index = 0)

In [28]:
all_cavs_stats_dfs['AVERAGE_BUCKETS'] = all_cavs_stats_dfs['FGM'] + all_cavs_stats_dfs['FTM'] + all_cavs_stats_dfs['AST']
all_cavs_stats_dfs['AVERAGE_STOPS'] = all_cavs_stats_dfs['DREB'] + all_cavs_stats_dfs['STL'] + all_cavs_stats_dfs['BLK']

In [47]:
cavs_career_stats = all_cavs_stats_dfs[[
    'PLAYER_ID',
    'SEASON_ID',
    'TEAM_ID',
    'MIN',
    'AVERAGE_BUCKETS',
    'AVERAGE_STOPS'
]]
cavs_career_stats.rename(columns = {'SEASON_ID': 'SEASON_YEAR', 'MIN': 'AVERAGE_MIN'}, inplace = True)
cavs_career_stats

/var/folders/zr/h0f224_d0qz617sgxs4f_0p40000gn/T/ipykernel_1136/1208359566.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cavs_career_stats.rename(columns = {'SEASON_ID': 'SEASON_YEAR', 'MIN': 'AVERAGE_MIN'}, inplace = True)

,PLAYER_ID,SEASON_YEAR,TEAM_ID,AVERAGE_MIN,AVERAGE_BUCKETS,AVERAGE_STOPS
0,1627747,2016-17,1610612751,21.7,6.1,3.9
1,1627747,2017-18,1610612751,26.2,10.6,4.4
2,1627747,2018-19,1610612751,26.6,11.2,4.4
3,1627747,2019-20,1610612751,29.6,14.4,4.5
4,1627747,2020-21,1610612751,27.8,15.5,5.1
...,...,...,...,...,...,...
0,1630600,2022-23,1610612739,3.3,0.5,1.4
0,1629731,2019-20,1610612739,6.0,1.0,1.8
1,1629731,2020-21,1610612739,19.2,3.8,3.7
2,1629731,2021-22,1610612739,19.2,3.3,3.0
3,1629731,2022-23,1610612739,24.1,3.7,4.6

In [48]:
cavs_merged_df_2 = pd.merge(
    cavs_merged_df,
    cavs_career_stats,
    how = 'inner',
    on = ['PLAYER_ID', 'TEAM_ID', 'SEASON_YEAR']
)
cavs_merged_df_2['BUCKET_UPLIFT'] = (cavs_merged_df_2['PLAYER_BUCKETS'] - cavs_merged_df_2['AVERAGE_BUCKETS']) / cavs_merged_df_2['AVERAGE_BUCKETS']
cavs_merged_df_2['STOP_UPLIFT'] = (cavs_merged_df_2['PLAYER_STOPS'] - cavs_merged_df_2['AVERAGE_STOPS']) / cavs_merged_df_2['AVERAGE_STOPS']
cavs_merged_df_2

,PLAYER_ID,PLAYER_NAME,TEAM_ID,GAME_ID,PLUS_MINUS,PLAYER_MIN,PLAYER_BUCKETS,PLAYER_STOPS,SEASON_YEAR,TEAM_ABBREVIATION,...,BUCKET_CONTRIBUTION,STOP_CONTRIBUTION,BUCKET_CONTRIBUTION_RATE,STOP_CONTRIBUTION_RATE,MIN_PERCENTAGE,AVERAGE_MIN,AVERAGE_BUCKETS,AVERAGE_STOPS,BUCKET_UPLIFT,STOP_UPLIFT
0,1627747,Caris LeVert,1610612739,0022200540,1,37.266667,14,6,2022-23,CLE,...,0.197183,0.122449,19.718310,12.244898,0.776389,30.7,10.0,4.4,0.400000,0.363636
1,1627747,Caris LeVert,1610612739,0022200524,-8,34.850000,12,5,2022-23,CLE,...,0.129032,0.131579,12.903226,13.157895,0.726042,30.7,10.0,4.4,0.200000,0.136364
2,1627747,Caris LeVert,1610612739,0022200498,-8,19.666667,5,3,2022-23,CLE,...,0.058140,0.088235,5.813953,8.823529,0.409722,30.7,10.0,4.4,-0.500000,-0.318182
3,1627747,Caris LeVert,1610612739,0022200484,0,18.033333,6,2,2022-23,CLE,...,0.071429,0.047619,7.142857,4.761905,0.375694,30.7,10.0,4.4,-0.400000,-0.545455
4,1627747,Caris LeVert,1610612739,0022200466,-6,32.283333,4,9,2022-23,CLE,...,0.047059,0.230769,4.705882,23.076923,0.672569,30.7,10.0,4.4,-0.600000,1.045455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,1629731,Dean Wade,1610612739,0022200072,20,38.928333,3,6,2022-23,CLE,...,0.033708,0.150000,3.370787,15.000000,0.734497,24.1,3.7,4.6,-0.189189,0.304348
363,1629731,Dean Wade,1610612739,0022200056,9,29.725000,4,4,2022-23,CLE,...,0.048780,0.100000,4.878049,10.000000,0.619271,24.1,3.7,4.6,0.081081,-0.130435
364,1629731,Dean Wade,1610612739,0022200039,19,21.315000,9,3,2022-23,CLE,...,0.109756,0.063830,10.975610,6.382979,0.402170,24.1,3.7,4.6,1.432432,-0.347826
365,1629731,Dean Wade,1610612739,0022200032,6,4.116667,3,2,2022-23,CLE,...,0.031250,0.040816,3.125000,4.081633,0.085764,24.1,3.7,4.6,-0.189189,-0.565217
366,1629731,Dean Wade,1610612739,0022200008,-11,21.693333,6,3,2022-23,CLE,...,0.073171,0.071429,7.317073,7.142857,0.451944,24.1,3.7,4.6,0.621622,-0.347826

In [17]:
cavs_team_game_averages_2 = cavs_merged_df_2[['TEAM_ID', 'GAME_ID', 'PLAYER_ID', 'BUCKET_UPLIFT', 'STOP_UPLIFT']]
cavs_team_game_averages_2 = cavs_team_game_averages_2.groupby(['TEAM_ID', 'GAME_ID']).agg(
    {
        'BUCKET_UPLIFT': 'sum', 
        'STOP_UPLIFT': 'sum',
        'PLAYER_ID': 'count'
    }
).reset_index().rename(columns = {'BUCKET_UPLIFT': 'TOT_BUCKET_UPLIFT', 'STOP_UPLIFT': 'TOT_STOP_UPLIFT', 'PLAYER_ID': 'TOT_PLAYERS'})
cavs_team_game_averages_2

       TEAM_ID     GAME_ID  TOT_BUCKET_UPLIFT  TOT_STOP_UPLIFT  TOT_PLAYERS
0   1610612739  0022200008          -1.502045        -1.556775           10
1   1610612739  0022200032           4.049199         4.090153           12
2   1610612739  0022200039           1.323572         0.970207           10
3   1610612739  0022200056           1.530427        -1.667777            9
4   1610612739  0022200072          -0.042161        -2.335365            9
5   1610612739  0022200090           0.199947        -3.449789           12
6   1610612739  0022200107          -2.362845         0.098090           10
7   1610612739  0022200120           4.652612         6.329481           11
8   1610612739  0022200140          -1.033769        -1.199104           10
9   1610612739  0022200158          -0.154399        -1.471418            9
10  1610612739  0022200171          -1.665509        -3.639276           10
11  1610612739  0022200182          -1.174232        -0.594319            8
12  1610612739  0022200193           2.097819        -1.551479           10
13  1610612739  0022200216          -1.077546         0.458979           12
14  1610612739  0022200225          -0.933855         0.949195            9
15  1610612739  0022200244           0.547727         0.138005           12
16  1610612739  0022200248           0.529468         0.684732            9
17  1610612739  0022200261          -2.487806        -3.649306           11
18  1610612739  0022200280           3.628211        -1.748534           11
19  1610612739  0022200295          -0.581097         1.526242           10
20  1610612739  0022200303           2.543231         2.248358           10
21  1610612739  0022200312           3.128991         3.924220           10
22  1610612739  0022200330          -3.485225        -2.976602           11
23  1610612739  0022200348          -4.015490         0.068228           10
24  1610612739  0022200360          -3.823918        -1.269544           11
25  1610612739  0022200381           0.322120         1.674641            8
26  1610612739  0022200390           2.637934         3.654362            9
27  1610612739  0022200406          -2.243096         0.063278            9
28  1610612739  0022200421          -2.622034        -1.628178           11
29  1610612739  0022200431          -1.143920        -1.726483            9
30  1610612739  0022200440          -1.824162         2.510988            9
31  1610612739  0022200452           0.382418         3.368673           10
32  1610612739  0022200466           0.087555        -0.145059            8
33  1610612739  0022200484           0.782182        -1.343347           11
34  1610612739  0022200498          -1.342290        -3.378909            9
35  1610612739  0022200524           1.931060        -1.264038            8
36  1610612739  0022200540           2.073870         3.830445           10

In [49]:
# cavs_team_game_averages = cavs_merged_df_2[['TEAM_ID', 'GAME_ID', 'BUCKET_UPLIFT', 'STOP_UPLIFT']]
# cavs_team_game_averages = cavs_team_game_averages.groupby(['TEAM_ID', 'GAME_ID']).mean().reset_index()
# cavs_team_game_averages.rename(columns = {'BUCKET_UPLIFT': 'AVG_BUCKET_UPLIFT', 'STOP_UPLIFT': 'AVG_STOP_UPLIFT'}, inplace = True)
# cavs_team_game_averages

In [50]:
cavs_merged_df_3 = pd.merge(
    cavs_merged_df_2,
    cavs_team_game_averages_2,
    how = 'inner',
    on = ['TEAM_ID', 'GAME_ID']
)
cavs_merged_df_3['AVG_TMT_BUCKET_UPLIFT'] = (cavs_merged_df_3['TOT_BUCKET_UPLIFT'] - cavs_merged_df_3['BUCKET_UPLIFT']) / (cavs_merged_df_3['TOT_PLAYERS'] - 1)
cavs_merged_df_3['TMT_BUCKET_UPLIFT_CONT_RATE'] = cavs_merged_df_3['MIN_PERCENTAGE'] * cavs_merged_df_3['AVG_TMT_BUCKET_UPLIFT'] * 100
cavs_merged_df_3['AVG_TMT_STOP_UPLIFT'] = (cavs_merged_df_3['TOT_STOP_UPLIFT'] - cavs_merged_df_3['STOP_UPLIFT']) / (cavs_merged_df_3['TOT_PLAYERS'] - 1)
cavs_merged_df_3['TMT_STOP_UPLIFT_CONT_RATE'] = cavs_merged_df_3['MIN_PERCENTAGE'] * cavs_merged_df_3['AVG_TMT_STOP_UPLIFT'] * 100
cavs_merged_df_3

,PLAYER_ID,PLAYER_NAME,TEAM_ID,GAME_ID,PLUS_MINUS,PLAYER_MIN,PLAYER_BUCKETS,PLAYER_STOPS,SEASON_YEAR,TEAM_ABBREVIATION,...,AVERAGE_STOPS,BUCKET_UPLIFT,STOP_UPLIFT,TOT_BUCKET_UPLIFT,TOT_STOP_UPLIFT,TOT_PLAYERS,AVG_TMT_BUCKET_UPLIFT,TMT_BUCKET_UPLIFT_CONT_RATE,AVG_TMT_STOP_UPLIFT,TMT_STOP_UPLIFT_CONT_RATE
0,1627747,Caris LeVert,1610612739,0022200540,1,37.266667,14,6,2022-23,CLE,...,4.4,0.400000,0.363636,2.073870,3.830445,10,0.185986,14.439713,0.385201,29.906578
1,1628378,Donovan Mitchell,1610612739,0022200540,-9,36.826667,16,6,2022-23,CLE,...,4.7,-0.166667,0.276596,2.073870,3.830445,10,0.248949,19.099885,0.394872,30.295472
2,1628386,Jarrett Allen,1610612739,0022200540,-3,34.870000,5,10,2022-23,CLE,...,9.2,-0.489796,0.086957,2.073870,3.830445,10,0.284852,20.693295,0.415943,30.216541
3,1630171,Isaac Okoro,1610612739,0022200540,2,22.940000,8,6,2022-23,CLE,...,2.7,1.222222,1.222222,2.073870,3.830445,10,0.094628,4.522408,0.289803,13.850148
4,1626224,Cedi Osman,1610612739,0022200540,9,24.530000,7,3,2022-23,CLE,...,2.9,0.111111,0.034483,2.073870,3.830445,10,0.218084,11.145018,0.421774,21.554390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,201577,Robin Lopez,1610612739,0022200248,5,10.250000,4,2,2022-23,CLE,...,0.9,0.818182,1.222222,0.529468,0.684732,9,-0.036089,-0.770655,-0.067186,-1.434706
363,1630205,Lamar Stevens,1610612739,0022200248,1,28.528333,4,3,2022-23,CLE,...,4.1,-0.024390,-0.268293,0.529468,0.684732,9,0.069232,4.114754,0.119128,7.080264
364,201567,Kevin Love,1610612739,0022200248,-1,11.716667,1,4,2022-23,CLE,...,6.5,-0.846154,-0.384615,0.529468,0.684732,9,0.171953,4.197319,0.133668,3.262810
365,1629636,Darius Garland,1610612739,0022200248,8,38.100000,24,1,2022-23,CLE,...,3.7,0.237113,-0.729730,0.529468,0.684732,9,0.036544,2.900707,0.176808,14.034115
366,1630596,Evan Mobley,1610612739,0022200248,5,35.550000,9,9,2022-23,CLE,...,8.5,-0.203540,0.058824,0.529468,0.684732,9,0.091626,6.786050,0.078239,5.794546

In [51]:
cavs_merged_df_3.columns

Index(['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'GAME_ID', 'PLUS_MINUS',
       'PLAYER_MIN', 'PLAYER_BUCKETS', 'PLAYER_STOPS', 'SEASON_YEAR',
       'TEAM_ABBREVIATION', 'TEAM_NAME', 'WL', 'GAME_MIN', 'GAME_BUCKETS',
       'GAME_STOPS', 'BUCKET_CONTRIBUTION', 'STOP_CONTRIBUTION',
       'BUCKET_CONTRIBUTION_RATE', 'STOP_CONTRIBUTION_RATE', 'MIN_PERCENTAGE',
       'AVERAGE_MIN', 'AVERAGE_BUCKETS', 'AVERAGE_STOPS', 'BUCKET_UPLIFT',
       'STOP_UPLIFT', 'TOT_BUCKET_UPLIFT', 'TOT_STOP_UPLIFT', 'TOT_PLAYERS',
       'AVG_TMT_BUCKET_UPLIFT', 'TMT_BUCKET_UPLIFT_CONT_RATE',
       'AVG_TMT_STOP_UPLIFT', 'TMT_STOP_UPLIFT_CONT_RATE'],
      dtype='object')

In [53]:
cavs_agg_df = cavs_merged_df_3[[
    'SEASON_YEAR', 
    'PLAYER_ID', 
    'PLAYER_NAME', 
    'TEAM_ID', 
    'TEAM_ABBREVIATION', 
    'TEAM_NAME',
    'AVERAGE_MIN',
    'PLUS_MINUS',
    'BUCKET_CONTRIBUTION_RATE',
    'STOP_CONTRIBUTION_RATE',
    'TMT_BUCKET_UPLIFT_CONT_RATE',
    'TMT_STOP_UPLIFT_CONT_RATE'
]]
cavs_agg_df = cavs_agg_df\
    .groupby(['SEASON_YEAR', 'PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME'])\
    .agg({
        'AVERAGE_MIN': 'mean',
        'PLUS_MINUS': 'sum',
        'BUCKET_CONTRIBUTION_RATE': 'mean', 
        'STOP_CONTRIBUTION_RATE': 'mean',
        'TMT_BUCKET_UPLIFT_CONT_RATE': 'mean',
        'TMT_STOP_UPLIFT_CONT_RATE': 'mean'
    }).reset_index()

In [55]:
cavs_agg_df['MIN_30_PLUS'] = cavs_agg_df['AVERAGE_MIN'].apply(lambda x: 1 if x > 30 else 0)

In [56]:
cavs_agg_df

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,AVERAGE_MIN,PLUS_MINUS,BUCKET_CONTRIBUTION_RATE,STOP_CONTRIBUTION_RATE,TMT_BUCKET_UPLIFT_CONT_RATE,TMT_STOP_UPLIFT_CONT_RATE,MIN_30_PLUS
0,2022-23,201567,Kevin Love,1610612739,CLE,Cleveland Cavaliers,20.3,114,7.800515,14.762016,-1.138555,-1.086489,0
1,2022-23,201577,Robin Lopez,1610612739,CLE,Cleveland Cavaliers,9.0,-7,2.802799,2.149564,1.715116,0.943715,0
2,2022-23,203526,Raul Neto,1610612739,CLE,Cleveland Cavaliers,9.2,21,3.254141,2.252939,2.016879,2.374224,0
3,2022-23,1626224,Cedi Osman,1610612739,CLE,Cleveland Cavaliers,22.9,182,7.593391,6.947413,0.654027,0.083446,0
4,2022-23,1627747,Caris LeVert,1610612739,CLE,Cleveland Cavaliers,30.7,109,12.067390,9.975993,-0.162176,1.158177,1
5,2022-23,1628378,Donovan Mitchell,1610612739,CLE,Cleveland Cavaliers,36.3,104,23.059700,10.776143,-3.807229,-3.615837,1
6,2022-23,1628386,Jarrett Allen,1610612739,CLE,Cleveland Cavaliers,33.5,139,11.454286,20.721244,-1.382691,-0.986432,1
7,2022-23,1629603,Mamadi Diakite,1610612739,CLE,Cleveland Cavaliers,7.1,4,1.301895,2.765173,-0.846867,0.790586,0
8,2022-23,1629636,Darius Garland,1610612739,CLE,Cleveland Cavaliers,35.9,107,23.597243,8.328161,-4.417274,-2.055365,1
9,2022-23,1629731,Dean Wade,1610612739,CLE,Cleveland Cavaliers,24.1,83,4.585264,10.393653,2.874682,-2.457558,0
10,2022-23,1630171,Isaac Okoro,1610612739,CLE,Cleveland Cavaliers,18.9,5,4.461392,6.258338,0.764195,1.033900,0
11,2022-23,1630205,Lamar Stevens,1610612739,CLE,Cleveland Cavaliers,23.0,-2,4.940842,9.528580,-2.785788,-1.102844,0
12,2022-23,1630596,Evan Mobley,1610612739,CLE,Cleveland Cavaliers,34.0,56,13.616494,19.553971,-1.814918,-1.390616,1
13,2022-23,1630600,Isaiah Mobley,1610612739,CLE,Cleveland Cavaliers,3.3,25,0.671467,3.213255,0.606577,0.229218,0

In [57]:
from sklearn.cluster import KMeans

/Users/erictria/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [64]:
km = KMeans(
    n_clusters=3, init='random',
    n_init=10, max_iter=300, 
    tol=1e-04, random_state=0
)
fit_arr = cavs_agg_df[[
    'PLUS_MINUS',
    'BUCKET_CONTRIBUTION_RATE',
    'STOP_CONTRIBUTION_RATE',
    'TMT_BUCKET_UPLIFT_CONT_RATE',
    'TMT_STOP_UPLIFT_CONT_RATE',
    'MIN_30_PLUS'
]].to_numpy()
fit_arr
#y_km = km.fit_predict(fit_arr)

array([[ 1.14000000e+02,  7.80051544e+00,  1.47620160e+01,
        -1.13855456e+00, -1.08648915e+00,  0.00000000e+00],
       [-7.00000000e+00,  2.80279926e+00,  2.14956431e+00,
         1.71511616e+00,  9.43715075e-01,  0.00000000e+00],
       [ 2.10000000e+01,  3.25414104e+00,  2.25293915e+00,
         2.01687932e+00,  2.37422422e+00,  0.00000000e+00],
       [ 1.82000000e+02,  7.59339071e+00,  6.94741275e+00,
         6.54027150e-01,  8.34462547e-02,  0.00000000e+00],
       [ 1.09000000e+02,  1.20673898e+01,  9.97599323e+00,
        -1.62175967e-01,  1.15817699e+00,  1.00000000e+00],
       [ 1.04000000e+02,  2.30597000e+01,  1.07761434e+01,
        -3.80722862e+00, -3.61583679e+00,  1.00000000e+00],
       [ 1.39000000e+02,  1.14542863e+01,  2.07212437e+01,
        -1.38269108e+00, -9.86432058e-01,  1.00000000e+00],
       [ 4.00000000e+00,  1.30189526e+00,  2.76517301e+00,
        -8.46867317e-01,  7.90586007e-01,  0.00000000e+00],
       [ 1.07000000e+02,  2.35972426e+01,  8.32816147e+00,
        -4.41727398e+00, -2.05536452e+00,  1.00000000e+00],
       [ 8.30000000e+01,  4.58526412e+00,  1.03936529e+01,
         2.87468179e+00, -2.45755804e+00,  0.00000000e+00],
       [ 5.00000000e+00,  4.46139187e+00,  6.25833755e+00,
         7.64195300e-01,  1.03390008e+00,  0.00000000e+00],
       [-2.00000000e+00,  4.94084188e+00,  9.52858026e+00,
        -2.78578784e+00, -1.10284430e+00,  0.00000000e+00],
       [ 5.60000000e+01,  1.36164937e+01,  1.95539709e+01,
        -1.81491846e+00, -1.39061642e+00,  1.00000000e+00],
       [ 2.50000000e+01,  6.71466503e-01,  3.21325500e+00,
         6.06576548e-01,  2.29218309e-01,  0.00000000e+00]])